import type { CatalogItem } from '../schema/catalogTypes';

export type AchievementCategory = 'longevity' | 'wealth' | 'career' | 'relationship' | 'crime';

export interface AchievementCatalogItem extends CatalogItem {
  category: AchievementCategory;
  targetValue: number;
}

const achievementSource = { sourceTitle: 'Achievements', sourcePage: 'Achievements' };

export const achievements: AchievementCatalogItem[] = [
  {
    id: 'achievement.long_life',
    titleKey: 'catalog.achievement.longLife.title',
    summaryKey: 'catalog.achievement.longLife.summary',
    category: 'longevity',
    targetValue: 80,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.first_million',
    titleKey: 'catalog.achievement.firstMillion.title',
    summaryKey: 'catalog.achievement.firstMillion.summary',
    category: 'wealth',
    targetValue: 1000000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.steady_career',
    titleKey: 'catalog.achievement.steadyCareer.title',
    summaryKey: 'catalog.achievement.steadyCareer.summary',
    category: 'career',
    targetValue: 10,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.family_anchor',
    titleKey: 'catalog.achievement.familyAnchor.title',
    summaryKey: 'catalog.achievement.familyAnchor.summary',
    category: 'relationship',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.second_chance',
    titleKey: 'catalog.achievement.secondChance.title',
    summaryKey: 'catalog.achievement.secondChance.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.first_steps_goal',
    titleKey: 'catalog.achievement.firstStepsGoal.title',
    summaryKey: 'catalog.achievement.firstStepsGoal.summary',
    category: 'longevity',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.teen_milestone',
    titleKey: 'catalog.achievement.teenMilestone.title',
    summaryKey: 'catalog.achievement.teenMilestone.summary',
    category: 'longevity',
    targetValue: 13,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.adult_milestone',
    titleKey: 'catalog.achievement.adultMilestone.title',
    summaryKey: 'catalog.achievement.adultMilestone.summary',
    category: 'longevity',
    targetValue: 18,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.thirty_candles',
    titleKey: 'catalog.achievement.thirtyCandles.title',
    summaryKey: 'catalog.achievement.thirtyCandles.summary',
    category: 'longevity',
    targetValue: 30,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.midlife_marker',
    titleKey: 'catalog.achievement.midlifeMarker.title',
    summaryKey: 'catalog.achievement.midlifeMarker.summary',
    category: 'longevity',
    targetValue: 45,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.silver_years',
    titleKey: 'catalog.achievement.silverYears.title',
    summaryKey: 'catalog.achievement.silverYears.summary',
    category: 'longevity',
    targetValue: 60,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.golden_years',
    titleKey: 'catalog.achievement.goldenYears.title',
    summaryKey: 'catalog.achievement.goldenYears.summary',
    category: 'longevity',
    targetValue: 65,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.seventy_strong',
    titleKey: 'catalog.achievement.seventyStrong.title',
    summaryKey: 'catalog.achievement.seventyStrong.summary',
    category: 'longevity',
    targetValue: 70,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.eighty_five_club',
    titleKey: 'catalog.achievement.eightyFiveClub.title',
    summaryKey: 'catalog.achievement.eightyFiveClub.summary',
    category: 'longevity',
    targetValue: 85,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.ninety_years',
    titleKey: 'catalog.achievement.ninetyYears.title',
    summaryKey: 'catalog.achievement.ninetyYears.summary',
    category: 'longevity',
    targetValue: 90,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.century_life',
    titleKey: 'catalog.achievement.centuryLife.title',
    summaryKey: 'catalog.achievement.centuryLife.summary',
    category: 'longevity',
    targetValue: 100,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.healthy_routine',
    titleKey: 'catalog.achievement.healthyRoutine.title',
    summaryKey: 'catalog.achievement.healthyRoutine.summary',
    category: 'longevity',
    targetValue: 20,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.calm_decades',
    titleKey: 'catalog.achievement.calmDecades.title',
    summaryKey: 'catalog.achievement.calmDecades.summary',
    category: 'longevity',
    targetValue: 50,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.elder_learner',
    titleKey: 'catalog.achievement.elderLearner.title',
    summaryKey: 'catalog.achievement.elderLearner.summary',
    category: 'longevity',
    targetValue: 70,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.last_chapter_grace',
    titleKey: 'catalog.achievement.lastChapterGrace.title',
    summaryKey: 'catalog.achievement.lastChapterGrace.summary',
    category: 'longevity',
    targetValue: 80,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.rainy_day_fund',
    titleKey: 'catalog.achievement.rainyDayFund.title',
    summaryKey: 'catalog.achievement.rainyDayFund.summary',
    category: 'wealth',
    targetValue: 5000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.first_ten_thousand',
    titleKey: 'catalog.achievement.firstTenThousand.title',
    summaryKey: 'catalog.achievement.firstTenThousand.summary',
    category: 'wealth',
    targetValue: 10000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.car_buyer',
    titleKey: 'catalog.achievement.carBuyer.title',
    summaryKey: 'catalog.achievement.carBuyer.summary',
    category: 'wealth',
    targetValue: 20000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.home_down_payment',
    titleKey: 'catalog.achievement.homeDownPayment.title',
    summaryKey: 'catalog.achievement.homeDownPayment.summary',
    category: 'wealth',
    targetValue: 50000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.comfortable_savings',
    titleKey: 'catalog.achievement.comfortableSavings.title',
    summaryKey: 'catalog.achievement.comfortableSavings.summary',
    category: 'wealth',
    targetValue: 100000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.six_figure_balance',
    titleKey: 'catalog.achievement.sixFigureBalance.title',
    summaryKey: 'catalog.achievement.sixFigureBalance.summary',
    category: 'wealth',
    targetValue: 100000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.asset_collector',
    titleKey: 'catalog.achievement.assetCollector.title',
    summaryKey: 'catalog.achievement.assetCollector.summary',
    category: 'wealth',
    targetValue: 3,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.property_owner',
    titleKey: 'catalog.achievement.propertyOwner.title',
    summaryKey: 'catalog.achievement.propertyOwner.summary',
    category: 'wealth',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.luxury_purchase',
    titleKey: 'catalog.achievement.luxuryPurchase.title',
    summaryKey: 'catalog.achievement.luxuryPurchase.summary',
    category: 'wealth',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.debt_free_dream',
    titleKey: 'catalog.achievement.debtFreeDream.title',
    summaryKey: 'catalog.achievement.debtFreeDream.summary',
    category: 'wealth',
    targetValue: 0,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.investment_starter',
    titleKey: 'catalog.achievement.investmentStarter.title',
    summaryKey: 'catalog.achievement.investmentStarter.summary',
    category: 'wealth',
    targetValue: 25000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.half_million',
    titleKey: 'catalog.achievement.halfMillion.title',
    summaryKey: 'catalog.achievement.halfMillion.summary',
    category: 'wealth',
    targetValue: 500000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.two_million_mark',
    titleKey: 'catalog.achievement.twoMillionMark.title',
    summaryKey: 'catalog.achievement.twoMillionMark.summary',
    category: 'wealth',
    targetValue: 2000000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.high_upkeep_life',
    titleKey: 'catalog.achievement.highUpkeepLife.title',
    summaryKey: 'catalog.achievement.highUpkeepLife.summary',
    category: 'wealth',
    targetValue: 10000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.legacy_estate',
    titleKey: 'catalog.achievement.legacyEstate.title',
    summaryKey: 'catalog.achievement.legacyEstate.summary',
    category: 'wealth',
    targetValue: 750000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.first_paycheck',
    titleKey: 'catalog.achievement.firstPaycheck.title',
    summaryKey: 'catalog.achievement.firstPaycheck.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.promoted_once',
    titleKey: 'catalog.achievement.promotedOnce.title',
    summaryKey: 'catalog.achievement.promotedOnce.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.five_year_role',
    titleKey: 'catalog.achievement.fiveYearRole.title',
    summaryKey: 'catalog.achievement.fiveYearRole.summary',
    category: 'career',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.skilled_worker',
    titleKey: 'catalog.achievement.skilledWorker.title',
    summaryKey: 'catalog.achievement.skilledWorker.summary',
    category: 'career',
    targetValue: 3,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.professional_track',
    titleKey: 'catalog.achievement.professionalTrack.title',
    summaryKey: 'catalog.achievement.professionalTrack.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.high_earner',
    titleKey: 'catalog.achievement.highEarner.title',
    summaryKey: 'catalog.achievement.highEarner.summary',
    category: 'career',
    targetValue: 90000,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.medical_path',
    titleKey: 'catalog.achievement.medicalPath.title',
    summaryKey: 'catalog.achievement.medicalPath.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.legal_path',
    titleKey: 'catalog.achievement.legalPath.title',
    summaryKey: 'catalog.achievement.legalPath.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.tech_path',
    titleKey: 'catalog.achievement.techPath.title',
    summaryKey: 'catalog.achievement.techPath.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.public_service',
    titleKey: 'catalog.achievement.publicService.title',
    summaryKey: 'catalog.achievement.publicService.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.executive_desk',
    titleKey: 'catalog.achievement.executiveDesk.title',
    summaryKey: 'catalog.achievement.executiveDesk.summary',
    category: 'career',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.career_pivot',
    titleKey: 'catalog.achievement.careerPivot.title',
    summaryKey: 'catalog.achievement.careerPivot.summary',
    category: 'career',
    targetValue: 2,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.retired_worker',
    titleKey: 'catalog.achievement.retiredWorker.title',
    summaryKey: 'catalog.achievement.retiredWorker.summary',
    category: 'career',
    targetValue: 65,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.top_tier_career',
    titleKey: 'catalog.achievement.topTierCareer.title',
    summaryKey: 'catalog.achievement.topTierCareer.summary',
    category: 'career',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.work_legend',
    titleKey: 'catalog.achievement.workLegend.title',
    summaryKey: 'catalog.achievement.workLegend.summary',
    category: 'career',
    targetValue: 30,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.new_friend_goal',
    titleKey: 'catalog.achievement.newFriendGoal.title',
    summaryKey: 'catalog.achievement.newFriendGoal.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.loyal_friend',
    titleKey: 'catalog.achievement.loyalFriend.title',
    summaryKey: 'catalog.achievement.loyalFriend.summary',
    category: 'relationship',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.first_love_goal',
    titleKey: 'catalog.achievement.firstLoveGoal.title',
    summaryKey: 'catalog.achievement.firstLoveGoal.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.married_life',
    titleKey: 'catalog.achievement.marriedLife.title',
    summaryKey: 'catalog.achievement.marriedLife.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.parent_life',
    titleKey: 'catalog.achievement.parentLife.title',
    summaryKey: 'catalog.achievement.parentLife.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.family_circle',
    titleKey: 'catalog.achievement.familyCircle.title',
    summaryKey: 'catalog.achievement.familyCircle.summary',
    category: 'relationship',
    targetValue: 4,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.grandparent_bond',
    titleKey: 'catalog.achievement.grandparentBond.title',
    summaryKey: 'catalog.achievement.grandparentBond.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.reunion_keeper',
    titleKey: 'catalog.achievement.reunionKeeper.title',
    summaryKey: 'catalog.achievement.reunionKeeper.summary',
    category: 'relationship',
    targetValue: 3,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.anniversary_five',
    titleKey: 'catalog.achievement.anniversaryFive.title',
    summaryKey: 'catalog.achievement.anniversaryFive.summary',
    category: 'relationship',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.anniversary_twenty',
    titleKey: 'catalog.achievement.anniversaryTwenty.title',
    summaryKey: 'catalog.achievement.anniversaryTwenty.summary',
    category: 'relationship',
    targetValue: 20,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.community_helper',
    titleKey: 'catalog.achievement.communityHelper.title',
    summaryKey: 'catalog.achievement.communityHelper.summary',
    category: 'relationship',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.trusted_sibling',
    titleKey: 'catalog.achievement.trustedSibling.title',
    summaryKey: 'catalog.achievement.trustedSibling.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.household_harmony',
    titleKey: 'catalog.achievement.householdHarmony.title',
    summaryKey: 'catalog.achievement.householdHarmony.summary',
    category: 'relationship',
    targetValue: 80,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.mentor_figure',
    titleKey: 'catalog.achievement.mentorFigure.title',
    summaryKey: 'catalog.achievement.mentorFigure.summary',
    category: 'relationship',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.beloved_elder',
    titleKey: 'catalog.achievement.belovedElder.title',
    summaryKey: 'catalog.achievement.belovedElder.summary',
    category: 'relationship',
    targetValue: 70,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.risky_choice_goal',
    titleKey: 'catalog.achievement.riskyChoiceGoal.title',
    summaryKey: 'catalog.achievement.riskyChoiceGoal.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.petty_run',
    titleKey: 'catalog.achievement.pettyRun.title',
    summaryKey: 'catalog.achievement.pettyRun.summary',
    category: 'crime',
    targetValue: 3,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.case_closed',
    titleKey: 'catalog.achievement.caseClosed.title',
    summaryKey: 'catalog.achievement.caseClosed.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.prison_year_goal',
    titleKey: 'catalog.achievement.prisonYearGoal.title',
    summaryKey: 'catalog.achievement.prisonYearGoal.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.parole_hope',
    titleKey: 'catalog.achievement.paroleHope.title',
    summaryKey: 'catalog.achievement.paroleHope.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.appeal_filed',
    titleKey: 'catalog.achievement.appealFiled.title',
    summaryKey: 'catalog.achievement.appealFiled.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.crime_spree',
    titleKey: 'catalog.achievement.crimeSpree.title',
    summaryKey: 'catalog.achievement.crimeSpree.summary',
    category: 'crime',
    targetValue: 5,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.white_collar_path',
    titleKey: 'catalog.achievement.whiteCollarPath.title',
    summaryKey: 'catalog.achievement.whiteCollarPath.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.shadow_network',
    titleKey: 'catalog.achievement.shadowNetwork.title',
    summaryKey: 'catalog.achievement.shadowNetwork.summary',
    category: 'crime',
    targetValue: 3,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.reform_path',
    titleKey: 'catalog.achievement.reformPath.title',
    summaryKey: 'catalog.achievement.reformPath.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.hard_time',
    titleKey: 'catalog.achievement.hardTime.title',
    summaryKey: 'catalog.achievement.hardTime.summary',
    category: 'crime',
    targetValue: 10,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.repeat_offender',
    titleKey: 'catalog.achievement.repeatOffender.title',
    summaryKey: 'catalog.achievement.repeatOffender.summary',
    category: 'crime',
    targetValue: 2,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.prison_scholar_goal',
    titleKey: 'catalog.achievement.prisonScholarGoal.title',
    summaryKey: 'catalog.achievement.prisonScholarGoal.summary',
    category: 'crime',
    targetValue: 1,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.second_chance_plus',
    titleKey: 'catalog.achievement.secondChancePlus.title',
    summaryKey: 'catalog.achievement.secondChancePlus.summary',
    category: 'crime',
    targetValue: 2,
    sourceRefs: [achievementSource],
  },
  {
    id: 'achievement.notorious_name',
    titleKey: 'catalog.achievement.notoriousName.title',
    summaryKey: 'catalog.achievement.notoriousName.summary',
    category: 'crime',
    targetValue: 10,
    sourceRefs: [achievementSource],
  },
];
