import type { CatalogItem } from '../schema/catalogTypes';

export type AssetCategory = 'home' | 'car' | 'aircraft' | 'boat' | 'jewelry';

export interface AssetCatalogItem extends CatalogItem {
  category: AssetCategory;
  price: number;
  yearlyUpkeep: number;
}

const assetsSource = { sourceTitle: 'Assets', sourcePage: 'Assets' };

export const assets: AssetCatalogItem[] = [
  {
    id: 'asset.starter_condo',
    titleKey: 'catalog.asset.starterCondo.title',
    summaryKey: 'catalog.asset.starterCondo.summary',
    category: 'home',
    price: 85000,
    yearlyUpkeep: 1800,
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets', sourceSection: 'Real Estate' }],
  },
  {
    id: 'asset.used_compact',
    titleKey: 'catalog.asset.usedCompact.title',
    summaryKey: 'catalog.asset.usedCompact.summary',
    category: 'car',
    price: 9000,
    yearlyUpkeep: 700,
    sourceRefs: [{ sourceTitle: 'Car', sourcePage: 'Car' }],
  },
  {
    id: 'asset.small_sailboat',
    titleKey: 'catalog.asset.smallSailboat.title',
    summaryKey: 'catalog.asset.smallSailboat.summary',
    category: 'boat',
    price: 24000,
    yearlyUpkeep: 1200,
    sourceRefs: [{ sourceTitle: 'Boat', sourcePage: 'Boat' }],
  },
  {
    id: 'asset.training_plane',
    titleKey: 'catalog.asset.trainingPlane.title',
    summaryKey: 'catalog.asset.trainingPlane.summary',
    category: 'aircraft',
    price: 95000,
    yearlyUpkeep: 9000,
    sourceRefs: [{ sourceTitle: 'Aircraft', sourcePage: 'Aircraft' }],
  },
  {
    id: 'asset.gold_watch',
    titleKey: 'catalog.asset.goldWatch.title',
    summaryKey: 'catalog.asset.goldWatch.summary',
    category: 'jewelry',
    price: 3500,
    yearlyUpkeep: 50,
    sourceRefs: [{ sourceTitle: 'Jewelry', sourcePage: 'Jewelry' }],
  },
  {
    id: 'asset.studio_apartment',
    titleKey: 'catalog.asset.studioApartment.title',
    summaryKey: 'catalog.asset.studioApartment.summary',
    category: 'home',
    price: 65000,
    yearlyUpkeep: 1400,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.suburban_townhouse',
    titleKey: 'catalog.asset.suburbanTownhouse.title',
    summaryKey: 'catalog.asset.suburbanTownhouse.summary',
    category: 'home',
    price: 145000,
    yearlyUpkeep: 2800,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.brick_duplex',
    titleKey: 'catalog.asset.brickDuplex.title',
    summaryKey: 'catalog.asset.brickDuplex.summary',
    category: 'home',
    price: 190000,
    yearlyUpkeep: 3600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.family_house',
    titleKey: 'catalog.asset.familyHouse.title',
    summaryKey: 'catalog.asset.familyHouse.summary',
    category: 'home',
    price: 260000,
    yearlyUpkeep: 5200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.city_loft',
    titleKey: 'catalog.asset.cityLoft.title',
    summaryKey: 'catalog.asset.cityLoft.summary',
    category: 'home',
    price: 310000,
    yearlyUpkeep: 6400,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.lake_cabin',
    titleKey: 'catalog.asset.lakeCabin.title',
    summaryKey: 'catalog.asset.lakeCabin.summary',
    category: 'home',
    price: 180000,
    yearlyUpkeep: 4100,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.beach_cottage',
    titleKey: 'catalog.asset.beachCottage.title',
    summaryKey: 'catalog.asset.beachCottage.summary',
    category: 'home',
    price: 340000,
    yearlyUpkeep: 7600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.rental_condo',
    titleKey: 'catalog.asset.rentalCondo.title',
    summaryKey: 'catalog.asset.rentalCondo.summary',
    category: 'home',
    price: 220000,
    yearlyUpkeep: 4800,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.modern_penthouse',
    titleKey: 'catalog.asset.modernPenthouse.title',
    summaryKey: 'catalog.asset.modernPenthouse.summary',
    category: 'home',
    price: 720000,
    yearlyUpkeep: 15000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.country_farmhouse',
    titleKey: 'catalog.asset.countryFarmhouse.title',
    summaryKey: 'catalog.asset.countryFarmhouse.summary',
    category: 'home',
    price: 275000,
    yearlyUpkeep: 6900,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.small_villa',
    titleKey: 'catalog.asset.smallVilla.title',
    summaryKey: 'catalog.asset.smallVilla.summary',
    category: 'home',
    price: 520000,
    yearlyUpkeep: 11200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.retirement_bungalow',
    titleKey: 'catalog.asset.retirementBungalow.title',
    summaryKey: 'catalog.asset.retirementBungalow.summary',
    category: 'home',
    price: 210000,
    yearlyUpkeep: 3600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.compact_car',
    titleKey: 'catalog.asset.compactCar.title',
    summaryKey: 'catalog.asset.compactCar.summary',
    category: 'car',
    price: 12000,
    yearlyUpkeep: 750,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.used_sedan',
    titleKey: 'catalog.asset.usedSedan.title',
    summaryKey: 'catalog.asset.usedSedan.summary',
    category: 'car',
    price: 15000,
    yearlyUpkeep: 850,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.hybrid_hatchback',
    titleKey: 'catalog.asset.hybridHatchback.title',
    summaryKey: 'catalog.asset.hybridHatchback.summary',
    category: 'car',
    price: 24000,
    yearlyUpkeep: 950,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.pickup_truck',
    titleKey: 'catalog.asset.pickupTruck.title',
    summaryKey: 'catalog.asset.pickupTruck.summary',
    category: 'car',
    price: 32000,
    yearlyUpkeep: 1400,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.family_minivan',
    titleKey: 'catalog.asset.familyMinivan.title',
    summaryKey: 'catalog.asset.familyMinivan.summary',
    category: 'car',
    price: 28000,
    yearlyUpkeep: 1200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.sports_coupe',
    titleKey: 'catalog.asset.sportsCoupe.title',
    summaryKey: 'catalog.asset.sportsCoupe.summary',
    category: 'car',
    price: 62000,
    yearlyUpkeep: 2600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.electric_sedan',
    titleKey: 'catalog.asset.electricSedan.title',
    summaryKey: 'catalog.asset.electricSedan.summary',
    category: 'car',
    price: 52000,
    yearlyUpkeep: 1700,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.luxury_suv',
    titleKey: 'catalog.asset.luxurySuv.title',
    summaryKey: 'catalog.asset.luxurySuv.summary',
    category: 'car',
    price: 84000,
    yearlyUpkeep: 3400,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.classic_roadster',
    titleKey: 'catalog.asset.classicRoadster.title',
    summaryKey: 'catalog.asset.classicRoadster.summary',
    category: 'car',
    price: 70000,
    yearlyUpkeep: 4200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.rideshare_car',
    titleKey: 'catalog.asset.rideshareCar.title',
    summaryKey: 'catalog.asset.rideshareCar.summary',
    category: 'car',
    price: 26000,
    yearlyUpkeep: 1500,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.delivery_van',
    titleKey: 'catalog.asset.deliveryVan.title',
    summaryKey: 'catalog.asset.deliveryVan.summary',
    category: 'car',
    price: 36000,
    yearlyUpkeep: 1800,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.executive_sedan',
    titleKey: 'catalog.asset.executiveSedan.title',
    summaryKey: 'catalog.asset.executiveSedan.summary',
    category: 'car',
    price: 92000,
    yearlyUpkeep: 3800,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.fishing_boat',
    titleKey: 'catalog.asset.fishingBoat.title',
    summaryKey: 'catalog.asset.fishingBoat.summary',
    category: 'boat',
    price: 18000,
    yearlyUpkeep: 1100,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.speedboat',
    titleKey: 'catalog.asset.speedboat.title',
    summaryKey: 'catalog.asset.speedboat.summary',
    category: 'boat',
    price: 48000,
    yearlyUpkeep: 2600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.pontoon_boat',
    titleKey: 'catalog.asset.pontoonBoat.title',
    summaryKey: 'catalog.asset.pontoonBoat.summary',
    category: 'boat',
    price: 36000,
    yearlyUpkeep: 1900,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.cabin_cruiser',
    titleKey: 'catalog.asset.cabinCruiser.title',
    summaryKey: 'catalog.asset.cabinCruiser.summary',
    category: 'boat',
    price: 88000,
    yearlyUpkeep: 5200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.houseboat',
    titleKey: 'catalog.asset.houseboat.title',
    summaryKey: 'catalog.asset.houseboat.summary',
    category: 'boat',
    price: 135000,
    yearlyUpkeep: 7600,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.yacht_share',
    titleKey: 'catalog.asset.yachtShare.title',
    summaryKey: 'catalog.asset.yachtShare.summary',
    category: 'boat',
    price: 210000,
    yearlyUpkeep: 12000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.sport_yacht',
    titleKey: 'catalog.asset.sportYacht.title',
    summaryKey: 'catalog.asset.sportYacht.summary',
    category: 'boat',
    price: 420000,
    yearlyUpkeep: 26000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.river_kayak',
    titleKey: 'catalog.asset.riverKayak.title',
    summaryKey: 'catalog.asset.riverKayak.summary',
    category: 'boat',
    price: 1800,
    yearlyUpkeep: 180,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.ultralight_plane',
    titleKey: 'catalog.asset.ultralightPlane.title',
    summaryKey: 'catalog.asset.ultralightPlane.summary',
    category: 'aircraft',
    price: 42000,
    yearlyUpkeep: 5200,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.private_helicopter',
    titleKey: 'catalog.asset.privateHelicopter.title',
    summaryKey: 'catalog.asset.privateHelicopter.summary',
    category: 'aircraft',
    price: 380000,
    yearlyUpkeep: 36000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.vintage_biplane',
    titleKey: 'catalog.asset.vintageBiplane.title',
    summaryKey: 'catalog.asset.vintageBiplane.summary',
    category: 'aircraft',
    price: 160000,
    yearlyUpkeep: 18000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.twin_engine_plane',
    titleKey: 'catalog.asset.twinEnginePlane.title',
    summaryKey: 'catalog.asset.twinEnginePlane.summary',
    category: 'aircraft',
    price: 520000,
    yearlyUpkeep: 48000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.business_jet_share',
    titleKey: 'catalog.asset.businessJetShare.title',
    summaryKey: 'catalog.asset.businessJetShare.summary',
    category: 'aircraft',
    price: 900000,
    yearlyUpkeep: 72000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.personal_jet',
    titleKey: 'catalog.asset.personalJet.title',
    summaryKey: 'catalog.asset.personalJet.summary',
    category: 'aircraft',
    price: 2400000,
    yearlyUpkeep: 180000,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.silver_necklace',
    titleKey: 'catalog.asset.silverNecklace.title',
    summaryKey: 'catalog.asset.silverNecklace.summary',
    category: 'jewelry',
    price: 900,
    yearlyUpkeep: 20,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.diamond_ring',
    titleKey: 'catalog.asset.diamondRing.title',
    summaryKey: 'catalog.asset.diamondRing.summary',
    category: 'jewelry',
    price: 6500,
    yearlyUpkeep: 80,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.pearl_earrings',
    titleKey: 'catalog.asset.pearlEarrings.title',
    summaryKey: 'catalog.asset.pearlEarrings.summary',
    category: 'jewelry',
    price: 2400,
    yearlyUpkeep: 45,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.luxury_bracelet',
    titleKey: 'catalog.asset.luxuryBracelet.title',
    summaryKey: 'catalog.asset.luxuryBracelet.summary',
    category: 'jewelry',
    price: 9000,
    yearlyUpkeep: 110,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.antique_brooch',
    titleKey: 'catalog.asset.antiqueBrooch.title',
    summaryKey: 'catalog.asset.antiqueBrooch.summary',
    category: 'jewelry',
    price: 5200,
    yearlyUpkeep: 75,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.platinum_chain',
    titleKey: 'catalog.asset.platinumChain.title',
    summaryKey: 'catalog.asset.platinumChain.summary',
    category: 'jewelry',
    price: 7800,
    yearlyUpkeep: 90,
    sourceRefs: [assetsSource],
  },
  {
    id: 'asset.heirloom_locket',
    titleKey: 'catalog.asset.heirloomLocket.title',
    summaryKey: 'catalog.asset.heirloomLocket.summary',
    category: 'jewelry',
    price: 4200,
    yearlyUpkeep: 50,
    sourceRefs: [assetsSource],
  },
];
