import type { CatalogItem } from '../schema/catalogTypes';

export type EducationLevel = 'none' | 'community_college' | 'university';

export interface CareerCatalogItem extends CatalogItem {
  salary: number;
  smartsMin: number;
  educationLevel: EducationLevel;
  tier: number;
}

const careersSource = { sourceTitle: 'Careers/Jobs', sourcePage: 'Careers/Jobs' };

export const careers: CareerCatalogItem[] = [
  {
    id: 'career.cashier',
    titleKey: 'catalog.career.cashier.title',
    summaryKey: 'catalog.career.cashier.summary',
    salary: 18000,
    smartsMin: 0,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.office_assistant',
    titleKey: 'catalog.career.officeAssistant.title',
    summaryKey: 'catalog.career.officeAssistant.summary',
    salary: 26000,
    smartsMin: 35,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.nurse_assistant',
    titleKey: 'catalog.career.nurseAssistant.title',
    summaryKey: 'catalog.career.nurseAssistant.summary',
    salary: 34000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.software_analyst',
    titleKey: 'catalog.career.softwareAnalyst.title',
    summaryKey: 'catalog.career.softwareAnalyst.summary',
    salary: 62000,
    smartsMin: 65,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.junior_law_clerk',
    titleKey: 'catalog.career.juniorLawClerk.title',
    summaryKey: 'catalog.career.juniorLawClerk.summary',
    salary: 52000,
    smartsMin: 70,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.barista',
    titleKey: 'catalog.career.barista.title',
    summaryKey: 'catalog.career.barista.summary',
    salary: 22000,
    smartsMin: 10,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.retail_manager',
    titleKey: 'catalog.career.retailManager.title',
    summaryKey: 'catalog.career.retailManager.summary',
    salary: 38000,
    smartsMin: 35,
    educationLevel: 'none',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.restaurant_server',
    titleKey: 'catalog.career.restaurantServer.title',
    summaryKey: 'catalog.career.restaurantServer.summary',
    salary: 24000,
    smartsMin: 15,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.line_cook',
    titleKey: 'catalog.career.lineCook.title',
    summaryKey: 'catalog.career.lineCook.summary',
    salary: 30000,
    smartsMin: 20,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.bus_driver',
    titleKey: 'catalog.career.busDriver.title',
    summaryKey: 'catalog.career.busDriver.summary',
    salary: 36000,
    smartsMin: 25,
    educationLevel: 'none',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.delivery_driver',
    titleKey: 'catalog.career.deliveryDriver.title',
    summaryKey: 'catalog.career.deliveryDriver.summary',
    salary: 32000,
    smartsMin: 20,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.security_guard',
    titleKey: 'catalog.career.securityGuard.title',
    summaryKey: 'catalog.career.securityGuard.summary',
    salary: 33000,
    smartsMin: 25,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.warehouse_worker',
    titleKey: 'catalog.career.warehouseWorker.title',
    summaryKey: 'catalog.career.warehouseWorker.summary',
    salary: 34000,
    smartsMin: 15,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.construction_worker',
    titleKey: 'catalog.career.constructionWorker.title',
    summaryKey: 'catalog.career.constructionWorker.summary',
    salary: 39000,
    smartsMin: 20,
    educationLevel: 'none',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.mechanic_apprentice',
    titleKey: 'catalog.career.mechanicApprentice.title',
    summaryKey: 'catalog.career.mechanicApprentice.summary',
    salary: 31000,
    smartsMin: 30,
    educationLevel: 'none',
    tier: 1,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.hair_stylist',
    titleKey: 'catalog.career.hairStylist.title',
    summaryKey: 'catalog.career.hairStylist.summary',
    salary: 35000,
    smartsMin: 25,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.travel_agent',
    titleKey: 'catalog.career.travelAgent.title',
    summaryKey: 'catalog.career.travelAgent.summary',
    salary: 42000,
    smartsMin: 40,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.paramedic',
    titleKey: 'catalog.career.paramedic.title',
    summaryKey: 'catalog.career.paramedic.summary',
    salary: 44000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.dental_hygienist',
    titleKey: 'catalog.career.dentalHygienist.title',
    summaryKey: 'catalog.career.dentalHygienist.summary',
    salary: 58000,
    smartsMin: 50,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.radiology_technician',
    titleKey: 'catalog.career.radiologyTechnician.title',
    summaryKey: 'catalog.career.radiologyTechnician.summary',
    salary: 56000,
    smartsMin: 55,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.lab_technician',
    titleKey: 'catalog.career.labTechnician.title',
    summaryKey: 'catalog.career.labTechnician.summary',
    salary: 50000,
    smartsMin: 55,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.paralegal',
    titleKey: 'catalog.career.paralegal.title',
    summaryKey: 'catalog.career.paralegal.summary',
    salary: 52000,
    smartsMin: 55,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.real_estate_agent',
    titleKey: 'catalog.career.realEstateAgent.title',
    summaryKey: 'catalog.career.realEstateAgent.summary',
    salary: 54000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.insurance_adjuster',
    titleKey: 'catalog.career.insuranceAdjuster.title',
    summaryKey: 'catalog.career.insuranceAdjuster.summary',
    salary: 56000,
    smartsMin: 50,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.bookkeeper',
    titleKey: 'catalog.career.bookkeeper.title',
    summaryKey: 'catalog.career.bookkeeper.summary',
    salary: 43000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.graphic_designer',
    titleKey: 'catalog.career.graphicDesigner.title',
    summaryKey: 'catalog.career.graphicDesigner.summary',
    salary: 52000,
    smartsMin: 50,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.web_developer',
    titleKey: 'catalog.career.webDeveloper.title',
    summaryKey: 'catalog.career.webDeveloper.summary',
    salary: 68000,
    smartsMin: 60,
    educationLevel: 'community_college',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.data_analyst',
    titleKey: 'catalog.career.dataAnalyst.title',
    summaryKey: 'catalog.career.dataAnalyst.summary',
    salary: 72000,
    smartsMin: 70,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.teacher',
    titleKey: 'catalog.career.teacher.title',
    summaryKey: 'catalog.career.teacher.summary',
    salary: 48000,
    smartsMin: 55,
    educationLevel: 'university',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.accountant',
    titleKey: 'catalog.career.accountant.title',
    summaryKey: 'catalog.career.accountant.summary',
    salary: 64000,
    smartsMin: 65,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.civil_engineer',
    titleKey: 'catalog.career.civilEngineer.title',
    summaryKey: 'catalog.career.civilEngineer.summary',
    salary: 76000,
    smartsMin: 70,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.mechanical_engineer',
    titleKey: 'catalog.career.mechanicalEngineer.title',
    summaryKey: 'catalog.career.mechanicalEngineer.summary',
    salary: 78000,
    smartsMin: 72,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.architect',
    titleKey: 'catalog.career.architect.title',
    summaryKey: 'catalog.career.architect.summary',
    salary: 82000,
    smartsMin: 75,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.pharmacist',
    titleKey: 'catalog.career.pharmacist.title',
    summaryKey: 'catalog.career.pharmacist.summary',
    salary: 104000,
    smartsMin: 78,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.veterinarian',
    titleKey: 'catalog.career.veterinarian.title',
    summaryKey: 'catalog.career.veterinarian.summary',
    salary: 98000,
    smartsMin: 76,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.physical_therapist',
    titleKey: 'catalog.career.physicalTherapist.title',
    summaryKey: 'catalog.career.physicalTherapist.summary',
    salary: 84000,
    smartsMin: 72,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.psychologist',
    titleKey: 'catalog.career.psychologist.title',
    summaryKey: 'catalog.career.psychologist.summary',
    salary: 90000,
    smartsMin: 80,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.dentist',
    titleKey: 'catalog.career.dentist.title',
    summaryKey: 'catalog.career.dentist.summary',
    salary: 132000,
    smartsMin: 82,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.physician',
    titleKey: 'catalog.career.physician.title',
    summaryKey: 'catalog.career.physician.summary',
    salary: 156000,
    smartsMin: 85,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.surgeon',
    titleKey: 'catalog.career.surgeon.title',
    summaryKey: 'catalog.career.surgeon.summary',
    salary: 220000,
    smartsMin: 90,
    educationLevel: 'university',
    tier: 5,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.judge',
    titleKey: 'catalog.career.judge.title',
    summaryKey: 'catalog.career.judge.summary',
    salary: 150000,
    smartsMin: 88,
    educationLevel: 'university',
    tier: 5,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.corporate_lawyer',
    titleKey: 'catalog.career.corporateLawyer.title',
    summaryKey: 'catalog.career.corporateLawyer.summary',
    salary: 145000,
    smartsMin: 86,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.university_professor',
    titleKey: 'catalog.career.universityProfessor.title',
    summaryKey: 'catalog.career.universityProfessor.summary',
    salary: 88000,
    smartsMin: 82,
    educationLevel: 'university',
    tier: 4,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.pilot',
    titleKey: 'catalog.career.pilot.title',
    summaryKey: 'catalog.career.pilot.summary',
    salary: 92000,
    smartsMin: 70,
    educationLevel: 'community_college',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.airline_captain',
    titleKey: 'catalog.career.airlineCaptain.title',
    summaryKey: 'catalog.career.airlineCaptain.summary',
    salary: 160000,
    smartsMin: 80,
    educationLevel: 'university',
    tier: 5,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.police_officer',
    titleKey: 'catalog.career.policeOfficer.title',
    summaryKey: 'catalog.career.policeOfficer.summary',
    salary: 52000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.detective',
    titleKey: 'catalog.career.detective.title',
    summaryKey: 'catalog.career.detective.summary',
    salary: 72000,
    smartsMin: 65,
    educationLevel: 'community_college',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.firefighter',
    titleKey: 'catalog.career.firefighter.title',
    summaryKey: 'catalog.career.firefighter.summary',
    salary: 54000,
    smartsMin: 45,
    educationLevel: 'community_college',
    tier: 2,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.chef',
    titleKey: 'catalog.career.chef.title',
    summaryKey: 'catalog.career.chef.summary',
    salary: 62000,
    smartsMin: 50,
    educationLevel: 'community_college',
    tier: 3,
    sourceRefs: [careersSource],
  },
  {
    id: 'career.marketing_manager',
    titleKey: 'catalog.career.marketingManager.title',
    summaryKey: 'catalog.career.marketingManager.summary',
    salary: 88000,
    smartsMin: 68,
    educationLevel: 'university',
    tier: 3,
    sourceRefs: [careersSource],
  },
];
