import type { CatalogItem, EffectConfig } from '../schema/catalogTypes';

export type CrimeSeverity = 'petty' | 'serious' | 'violent';

export interface CrimeCatalogItem extends CatalogItem {
  severity: CrimeSeverity;
  minAge: number;
  successChance: number;
  sentenceYears: number;
  effects: EffectConfig;
}

const crimeSource = { sourceTitle: 'Crime', sourcePage: 'Crime' };

export const crimes: CrimeCatalogItem[] = [
  {
    id: 'crime.shoplifting',
    titleKey: 'catalog.crime.shoplifting.title',
    summaryKey: 'catalog.crime.shoplifting.summary',
    severity: 'petty',
    minAge: 12,
    successChance: 0.65,
    sentenceYears: 1,
    effects: { money: 120, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.burglary',
    titleKey: 'catalog.crime.burglary.title',
    summaryKey: 'catalog.crime.burglary.summary',
    severity: 'serious',
    minAge: 16,
    successChance: 0.45,
    sentenceYears: 4,
    effects: { money: 1200, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.grand_theft_auto',
    titleKey: 'catalog.crime.grandTheftAuto.title',
    summaryKey: 'catalog.crime.grandTheftAuto.summary',
    severity: 'serious',
    minAge: 16,
    successChance: 0.35,
    sentenceYears: 5,
    effects: { money: 3500, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.bank_robbery',
    titleKey: 'catalog.crime.bankRobbery.title',
    summaryKey: 'catalog.crime.bankRobbery.summary',
    severity: 'violent',
    minAge: 18,
    successChance: 0.22,
    sentenceYears: 12,
    effects: { money: 25000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.fraud',
    titleKey: 'catalog.crime.fraud.title',
    summaryKey: 'catalog.crime.fraud.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.4,
    sentenceYears: 6,
    effects: { money: 6000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.pickpocketing',
    titleKey: 'catalog.crime.pickpocketing.title',
    summaryKey: 'catalog.crime.pickpocketing.summary',
    severity: 'petty',
    minAge: 12,
    successChance: 0.62,
    sentenceYears: 1,
    effects: { money: 180, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.vandalism',
    titleKey: 'catalog.crime.vandalism.title',
    summaryKey: 'catalog.crime.vandalism.summary',
    severity: 'petty',
    minAge: 12,
    successChance: 0.58,
    sentenceYears: 1,
    effects: { money: 80, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.porch_piracy',
    titleKey: 'catalog.crime.porchPiracy.title',
    summaryKey: 'catalog.crime.porchPiracy.summary',
    severity: 'petty',
    minAge: 13,
    successChance: 0.55,
    sentenceYears: 1,
    effects: { money: 260, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.identity_theft',
    titleKey: 'catalog.crime.identityTheft.title',
    summaryKey: 'catalog.crime.identityTheft.summary',
    severity: 'serious',
    minAge: 16,
    successChance: 0.38,
    sentenceYears: 4,
    effects: { money: 4500, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.tax_evasion',
    titleKey: 'catalog.crime.taxEvasion.title',
    summaryKey: 'catalog.crime.taxEvasion.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.42,
    sentenceYears: 5,
    effects: { money: 8000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.embezzlement',
    titleKey: 'catalog.crime.embezzlement.title',
    summaryKey: 'catalog.crime.embezzlement.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.36,
    sentenceYears: 6,
    effects: { money: 12000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.arson',
    titleKey: 'catalog.crime.arson.title',
    summaryKey: 'catalog.crime.arson.summary',
    severity: 'violent',
    minAge: 18,
    successChance: 0.24,
    sentenceYears: 10,
    effects: { money: 3000, addStatus: 'suspicious', attributes: { happiness: -3 } },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.assault',
    titleKey: 'catalog.crime.assault.title',
    summaryKey: 'catalog.crime.assault.summary',
    severity: 'violent',
    minAge: 16,
    successChance: 0.32,
    sentenceYears: 4,
    effects: { money: 0, addStatus: 'suspicious', attributes: { happiness: -3 } },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.kidnapping',
    titleKey: 'catalog.crime.kidnapping.title',
    summaryKey: 'catalog.crime.kidnapping.summary',
    severity: 'violent',
    minAge: 18,
    successChance: 0.18,
    sentenceYears: 14,
    effects: { money: 18000, addStatus: 'suspicious', attributes: { happiness: -3 } },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.extortion',
    titleKey: 'catalog.crime.extortion.title',
    summaryKey: 'catalog.crime.extortion.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.34,
    sentenceYears: 7,
    effects: { money: 9000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.money_laundering',
    titleKey: 'catalog.crime.moneyLaundering.title',
    summaryKey: 'catalog.crime.moneyLaundering.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.3,
    sentenceYears: 8,
    effects: { money: 16000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.drug_trafficking',
    titleKey: 'catalog.crime.drugTrafficking.title',
    summaryKey: 'catalog.crime.drugTrafficking.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.28,
    sentenceYears: 9,
    effects: { money: 14000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.cybercrime',
    titleKey: 'catalog.crime.cybercrime.title',
    summaryKey: 'catalog.crime.cybercrime.summary',
    severity: 'serious',
    minAge: 16,
    successChance: 0.4,
    sentenceYears: 5,
    effects: { money: 7000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.smuggling',
    titleKey: 'catalog.crime.smuggling.title',
    summaryKey: 'catalog.crime.smuggling.summary',
    severity: 'serious',
    minAge: 18,
    successChance: 0.31,
    sentenceYears: 7,
    effects: { money: 11000, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
  {
    id: 'crime.public_disorder',
    titleKey: 'catalog.crime.publicDisorder.title',
    summaryKey: 'catalog.crime.publicDisorder.summary',
    severity: 'petty',
    minAge: 12,
    successChance: 0.7,
    sentenceYears: 1,
    effects: { money: 60, addStatus: 'suspicious' },
    sourceRefs: [crimeSource],
  },
];
