import type { CatalogItem, EffectConfig } from '../schema/catalogTypes';

export type DiseaseSeverity = 'mild' | 'moderate' | 'severe';

export interface DiseaseCatalogItem extends CatalogItem {
  severity: DiseaseSeverity;
  yearlyHealthImpact: number;
  treatable: boolean;
  effects: EffectConfig;
}

const diseasesSource = { sourceTitle: 'Diseases', sourcePage: 'Diseases' };

export const diseases: DiseaseCatalogItem[] = [
  {
    id: 'disease.common_cold',
    titleKey: 'catalog.disease.commonCold.title',
    summaryKey: 'catalog.disease.commonCold.summary',
    severity: 'mild',
    yearlyHealthImpact: -4,
    treatable: true,
    effects: { addStatus: 'sick' },
    sourceRefs: [{ sourceTitle: 'Diseases', sourcePage: 'Diseases' }],
  },
  {
    id: 'disease.migraine',
    titleKey: 'catalog.disease.migraine.title',
    summaryKey: 'catalog.disease.migraine.summary',
    severity: 'moderate',
    yearlyHealthImpact: -7,
    treatable: true,
    effects: { attributes: { happiness: -3 }, addStatus: 'sick' },
    sourceRefs: [{ sourceTitle: 'Diseases', sourcePage: 'Diseases' }],
  },
  {
    id: 'disease.asthma',
    titleKey: 'catalog.disease.asthma.title',
    summaryKey: 'catalog.disease.asthma.summary',
    severity: 'moderate',
    yearlyHealthImpact: -6,
    treatable: true,
    effects: { attributes: { health: -3 }, addStatus: 'sick' },
    sourceRefs: [{ sourceTitle: 'Diseases', sourcePage: 'Diseases' }],
  },
  {
    id: 'disease.pneumonia',
    titleKey: 'catalog.disease.pneumonia.title',
    summaryKey: 'catalog.disease.pneumonia.summary',
    severity: 'severe',
    yearlyHealthImpact: -16,
    treatable: true,
    effects: { attributes: { health: -12 }, addStatus: 'sick' },
    sourceRefs: [{ sourceTitle: 'Diseases/Deadly diseases', sourcePage: 'Diseases/Deadly diseases' }],
  },
  {
    id: 'disease.cancer',
    titleKey: 'catalog.disease.cancer.title',
    summaryKey: 'catalog.disease.cancer.summary',
    severity: 'severe',
    yearlyHealthImpact: -22,
    treatable: true,
    effects: { attributes: { health: -18, happiness: -8 }, addStatus: 'sick' },
    sourceRefs: [{ sourceTitle: 'Diseases/Deadly diseases', sourcePage: 'Diseases/Deadly diseases' }],
  },
  {
    id: 'disease.seasonal_allergies',
    titleKey: 'catalog.disease.seasonalAllergies.title',
    summaryKey: 'catalog.disease.seasonalAllergies.summary',
    severity: 'mild',
    yearlyHealthImpact: -3,
    treatable: true,
    effects: { attributes: { health: -1, happiness: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.food_poisoning',
    titleKey: 'catalog.disease.foodPoisoning.title',
    summaryKey: 'catalog.disease.foodPoisoning.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { health: -5, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.strep_throat',
    titleKey: 'catalog.disease.strepThroat.title',
    summaryKey: 'catalog.disease.strepThroat.summary',
    severity: 'moderate',
    yearlyHealthImpact: -7,
    treatable: true,
    effects: { attributes: { health: -4, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.flu',
    titleKey: 'catalog.disease.flu.title',
    summaryKey: 'catalog.disease.flu.summary',
    severity: 'moderate',
    yearlyHealthImpact: -9,
    treatable: true,
    effects: { attributes: { health: -5, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.bronchitis',
    titleKey: 'catalog.disease.bronchitis.title',
    summaryKey: 'catalog.disease.bronchitis.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { health: -4, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.chickenpox',
    titleKey: 'catalog.disease.chickenpox.title',
    summaryKey: 'catalog.disease.chickenpox.summary',
    severity: 'mild',
    yearlyHealthImpact: -5,
    treatable: true,
    effects: { attributes: { health: -2, looks: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.sprained_ankle',
    titleKey: 'catalog.disease.sprainedAnkle.title',
    summaryKey: 'catalog.disease.sprainedAnkle.summary',
    severity: 'mild',
    yearlyHealthImpact: -4,
    treatable: true,
    effects: { attributes: { health: -2, happiness: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.broken_arm',
    titleKey: 'catalog.disease.brokenArm.title',
    summaryKey: 'catalog.disease.brokenArm.summary',
    severity: 'moderate',
    yearlyHealthImpact: -10,
    treatable: true,
    effects: { attributes: { health: -6, happiness: -3 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.concussion',
    titleKey: 'catalog.disease.concussion.title',
    summaryKey: 'catalog.disease.concussion.summary',
    severity: 'moderate',
    yearlyHealthImpact: -11,
    treatable: true,
    effects: { attributes: { health: -7, smarts: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.anxiety',
    titleKey: 'catalog.disease.anxiety.title',
    summaryKey: 'catalog.disease.anxiety.summary',
    severity: 'moderate',
    yearlyHealthImpact: -6,
    treatable: true,
    effects: { attributes: { happiness: -5, health: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.depression',
    titleKey: 'catalog.disease.depression.title',
    summaryKey: 'catalog.disease.depression.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { happiness: -7, health: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.insomnia',
    titleKey: 'catalog.disease.insomnia.title',
    summaryKey: 'catalog.disease.insomnia.summary',
    severity: 'mild',
    yearlyHealthImpact: -5,
    treatable: true,
    effects: { attributes: { health: -2, happiness: -3 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.diabetes',
    titleKey: 'catalog.disease.diabetes.title',
    summaryKey: 'catalog.disease.diabetes.summary',
    severity: 'moderate',
    yearlyHealthImpact: -9,
    treatable: true,
    effects: { attributes: { health: -5, happiness: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.hypertension',
    titleKey: 'catalog.disease.hypertension.title',
    summaryKey: 'catalog.disease.hypertension.summary',
    severity: 'moderate',
    yearlyHealthImpact: -7,
    treatable: true,
    effects: { attributes: { health: -4 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.arthritis',
    titleKey: 'catalog.disease.arthritis.title',
    summaryKey: 'catalog.disease.arthritis.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { health: -4, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.kidney_stones',
    titleKey: 'catalog.disease.kidneyStones.title',
    summaryKey: 'catalog.disease.kidneyStones.summary',
    severity: 'moderate',
    yearlyHealthImpact: -9,
    treatable: true,
    effects: { attributes: { health: -5, happiness: -4 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.appendicitis',
    titleKey: 'catalog.disease.appendicitis.title',
    summaryKey: 'catalog.disease.appendicitis.summary',
    severity: 'severe',
    yearlyHealthImpact: -15,
    treatable: true,
    effects: { attributes: { health: -10, happiness: -4 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.ulcer',
    titleKey: 'catalog.disease.ulcer.title',
    summaryKey: 'catalog.disease.ulcer.summary',
    severity: 'moderate',
    yearlyHealthImpact: -7,
    treatable: true,
    effects: { attributes: { health: -3, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.anemia',
    titleKey: 'catalog.disease.anemia.title',
    summaryKey: 'catalog.disease.anemia.summary',
    severity: 'moderate',
    yearlyHealthImpact: -6,
    treatable: true,
    effects: { attributes: { health: -3 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.ear_infection',
    titleKey: 'catalog.disease.earInfection.title',
    summaryKey: 'catalog.disease.earInfection.summary',
    severity: 'mild',
    yearlyHealthImpact: -4,
    treatable: true,
    effects: { attributes: { health: -2, happiness: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.sinus_infection',
    titleKey: 'catalog.disease.sinusInfection.title',
    summaryKey: 'catalog.disease.sinusInfection.summary',
    severity: 'mild',
    yearlyHealthImpact: -5,
    treatable: true,
    effects: { attributes: { health: -2, happiness: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.dermatitis',
    titleKey: 'catalog.disease.dermatitis.title',
    summaryKey: 'catalog.disease.dermatitis.summary',
    severity: 'mild',
    yearlyHealthImpact: -4,
    treatable: true,
    effects: { attributes: { health: -1, looks: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.back_pain',
    titleKey: 'catalog.disease.backPain.title',
    summaryKey: 'catalog.disease.backPain.summary',
    severity: 'moderate',
    yearlyHealthImpact: -7,
    treatable: true,
    effects: { attributes: { health: -3, happiness: -3 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.mono',
    titleKey: 'catalog.disease.mono.title',
    summaryKey: 'catalog.disease.mono.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { health: -4, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.covid',
    titleKey: 'catalog.disease.covid.title',
    summaryKey: 'catalog.disease.covid.summary',
    severity: 'moderate',
    yearlyHealthImpact: -10,
    treatable: true,
    effects: { attributes: { health: -6, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.heart_disease',
    titleKey: 'catalog.disease.heartDisease.title',
    summaryKey: 'catalog.disease.heartDisease.summary',
    severity: 'severe',
    yearlyHealthImpact: -18,
    treatable: true,
    effects: { attributes: { health: -14, happiness: -5 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.stroke',
    titleKey: 'catalog.disease.stroke.title',
    summaryKey: 'catalog.disease.stroke.summary',
    severity: 'severe',
    yearlyHealthImpact: -20,
    treatable: true,
    effects: { attributes: { health: -16, smarts: -3, happiness: -5 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.dementia',
    titleKey: 'catalog.disease.dementia.title',
    summaryKey: 'catalog.disease.dementia.summary',
    severity: 'severe',
    yearlyHealthImpact: -18,
    treatable: false,
    effects: { attributes: { health: -10, smarts: -8, happiness: -4 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.kidney_disease',
    titleKey: 'catalog.disease.kidneyDisease.title',
    summaryKey: 'catalog.disease.kidneyDisease.summary',
    severity: 'severe',
    yearlyHealthImpact: -16,
    treatable: true,
    effects: { attributes: { health: -11, happiness: -3 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.liver_disease',
    titleKey: 'catalog.disease.liverDisease.title',
    summaryKey: 'catalog.disease.liverDisease.summary',
    severity: 'severe',
    yearlyHealthImpact: -18,
    treatable: true,
    effects: { attributes: { health: -13, happiness: -4 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.tuberculosis',
    titleKey: 'catalog.disease.tuberculosis.title',
    summaryKey: 'catalog.disease.tuberculosis.summary',
    severity: 'severe',
    yearlyHealthImpact: -17,
    treatable: true,
    effects: { attributes: { health: -12, happiness: -4 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.hiv',
    titleKey: 'catalog.disease.hiv.title',
    summaryKey: 'catalog.disease.hiv.summary',
    severity: 'severe',
    yearlyHealthImpact: -14,
    treatable: true,
    effects: { attributes: { health: -9, happiness: -5 }, addStatus: 'frail' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.epilepsy',
    titleKey: 'catalog.disease.epilepsy.title',
    summaryKey: 'catalog.disease.epilepsy.summary',
    severity: 'moderate',
    yearlyHealthImpact: -8,
    treatable: true,
    effects: { attributes: { health: -4, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.osteoporosis',
    titleKey: 'catalog.disease.osteoporosis.title',
    summaryKey: 'catalog.disease.osteoporosis.summary',
    severity: 'moderate',
    yearlyHealthImpact: -9,
    treatable: true,
    effects: { attributes: { health: -5, happiness: -2 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
  {
    id: 'disease.cataracts',
    titleKey: 'catalog.disease.cataracts.title',
    summaryKey: 'catalog.disease.cataracts.summary',
    severity: 'mild',
    yearlyHealthImpact: -4,
    treatable: true,
    effects: { attributes: { health: -1, looks: -1 }, addStatus: 'sick' },
    sourceRefs: [diseasesSource],
  },
];
