import type { CatalogItem } from '../schema/catalogTypes';

export type EducationProgramLevel = 'secondary' | 'community_college' | 'university';

export interface EducationProgramCatalogItem extends CatalogItem {
  level: EducationProgramLevel;
  minAge: number;
  durationYears: number;
  tuition: number;
  smartsMin: number;
}

const educationSource = { sourceTitle: 'Careers', sourcePage: 'Careers', sourceSection: 'Education' };

export const educationPrograms: EducationProgramCatalogItem[] = [
  {
    id: 'education.high_school',
    titleKey: 'catalog.education.highSchool.title',
    summaryKey: 'catalog.education.highSchool.summary',
    level: 'secondary',
    minAge: 14,
    durationYears: 4,
    tuition: 0,
    smartsMin: 0,
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'education.community_college',
    titleKey: 'catalog.education.communityCollege.title',
    summaryKey: 'catalog.education.communityCollege.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 2,
    tuition: 6000,
    smartsMin: 35,
    sourceRefs: [{ sourceTitle: 'Community college', sourcePage: 'Community college' }],
  },
  {
    id: 'education.university',
    titleKey: 'catalog.education.university.title',
    summaryKey: 'catalog.education.university.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 16000,
    smartsMin: 55,
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers', sourceSection: 'Education' }],
  },
  {
    id: 'education.vocational_care',
    titleKey: 'catalog.education.vocationalCare.title',
    summaryKey: 'catalog.education.vocationalCare.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 1,
    tuition: 5000,
    smartsMin: 35,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.culinary_certificate',
    titleKey: 'catalog.education.culinaryCertificate.title',
    summaryKey: 'catalog.education.culinaryCertificate.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 1,
    tuition: 6500,
    smartsMin: 30,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.trade_school',
    titleKey: 'catalog.education.tradeSchool.title',
    summaryKey: 'catalog.education.tradeSchool.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 2,
    tuition: 8000,
    smartsMin: 35,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.police_academy',
    titleKey: 'catalog.education.policeAcademy.title',
    summaryKey: 'catalog.education.policeAcademy.summary',
    level: 'community_college',
    minAge: 19,
    durationYears: 1,
    tuition: 7000,
    smartsMin: 40,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.fire_academy',
    titleKey: 'catalog.education.fireAcademy.title',
    summaryKey: 'catalog.education.fireAcademy.summary',
    level: 'community_college',
    minAge: 19,
    durationYears: 1,
    tuition: 7000,
    smartsMin: 40,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.paramedic_program',
    titleKey: 'catalog.education.paramedicProgram.title',
    summaryKey: 'catalog.education.paramedicProgram.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 2,
    tuition: 9000,
    smartsMin: 45,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.nursing',
    titleKey: 'catalog.education.nursing.title',
    summaryKey: 'catalog.education.nursing.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 2,
    tuition: 12000,
    smartsMin: 50,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.dental_hygiene',
    titleKey: 'catalog.education.dentalHygiene.title',
    summaryKey: 'catalog.education.dentalHygiene.summary',
    level: 'community_college',
    minAge: 18,
    durationYears: 2,
    tuition: 14000,
    smartsMin: 50,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.computer_science',
    titleKey: 'catalog.education.computerScience.title',
    summaryKey: 'catalog.education.computerScience.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 24000,
    smartsMin: 65,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.business',
    titleKey: 'catalog.education.business.title',
    summaryKey: 'catalog.education.business.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 22000,
    smartsMin: 55,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.education',
    titleKey: 'catalog.education.education.title',
    summaryKey: 'catalog.education.education.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 20000,
    smartsMin: 55,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.accounting',
    titleKey: 'catalog.education.accounting.title',
    summaryKey: 'catalog.education.accounting.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 23000,
    smartsMin: 60,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.engineering',
    titleKey: 'catalog.education.engineering.title',
    summaryKey: 'catalog.education.engineering.summary',
    level: 'university',
    minAge: 18,
    durationYears: 4,
    tuition: 28000,
    smartsMin: 70,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.architecture',
    titleKey: 'catalog.education.architecture.title',
    summaryKey: 'catalog.education.architecture.summary',
    level: 'university',
    minAge: 18,
    durationYears: 5,
    tuition: 30000,
    smartsMin: 72,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.pharmacy',
    titleKey: 'catalog.education.pharmacy.title',
    summaryKey: 'catalog.education.pharmacy.summary',
    level: 'university',
    minAge: 18,
    durationYears: 6,
    tuition: 42000,
    smartsMin: 78,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.medicine',
    titleKey: 'catalog.education.medicine.title',
    summaryKey: 'catalog.education.medicine.summary',
    level: 'university',
    minAge: 22,
    durationYears: 6,
    tuition: 65000,
    smartsMin: 85,
    sourceRefs: [educationSource],
  },
  {
    id: 'education.law',
    titleKey: 'catalog.education.law.title',
    summaryKey: 'catalog.education.law.summary',
    level: 'university',
    minAge: 22,
    durationYears: 3,
    tuition: 52000,
    smartsMin: 82,
    sourceRefs: [educationSource],
  },
];
