import type { CatalogItem, EffectConfig } from '../schema/catalogTypes';

export type P1EventStage = 'child' | 'school' | 'adult' | 'elder';

export interface P1EventCatalogItem extends CatalogItem {
  stage: P1EventStage;
  weight: number;
  effects: EffectConfig;
}

export const p1Events: P1EventCatalogItem[] = [
  {
    id: 'p1_event.child_library_card',
    titleKey: 'catalog.event.childLibraryCard.title',
    summaryKey: 'catalog.event.childLibraryCard.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_shared_snack',
    titleKey: 'catalog.event.childSharedSnack.title',
    summaryKey: 'catalog.event.childSharedSnack.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.school_group_project',
    titleKey: 'catalog.event.schoolGroupProject.title',
    summaryKey: 'catalog.event.schoolGroupProject.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_bully_choice',
    titleKey: 'catalog.event.schoolBullyChoice.title',
    summaryKey: 'catalog.event.schoolBullyChoice.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { happiness: 2 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.work_extra_shift',
    titleKey: 'catalog.event.workExtraShift.title',
    summaryKey: 'catalog.event.workExtraShift.summary',
    stage: 'adult',
    weight: 4,
    effects: { money: 350, attributes: { health: -2, happiness: -1 } },
    sourceRefs: [{ sourceTitle: 'Careers/Job activities', sourcePage: 'Careers/Job activities' }],
  },
  {
    id: 'p1_event.relationship_old_friend',
    titleKey: 'catalog.event.relationshipOldFriend.title',
    summaryKey: 'catalog.event.relationshipOldFriend.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.asset_unexpected_bill',
    titleKey: 'catalog.event.assetUnexpectedBill.title',
    summaryKey: 'catalog.event.assetUnexpectedBill.summary',
    stage: 'adult',
    weight: 3,
    effects: { money: -450, attributes: { happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.health_checkup_note',
    titleKey: 'catalog.event.healthCheckupNote.title',
    summaryKey: 'catalog.event.healthCheckupNote.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { health: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.crime_witness',
    titleKey: 'catalog.event.crimeWitness.title',
    summaryKey: 'catalog.event.crimeWitness.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: -2 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Crime', sourcePage: 'Crime', sourceSection: 'Witnessing crimes' }],
  },
  {
    id: 'p1_event.elder_family_visit',
    titleKey: 'catalog.event.elderFamilyVisit.title',
    summaryKey: 'catalog.event.elderFamilyVisit.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: 4, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships', sourceSection: 'Family' }],
  },
  {
    id: 'p1_event.child_puppet_show',
    titleKey: 'catalog.event.childPuppetShow.title',
    summaryKey: 'catalog.event.childPuppetShow.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_lost_mittens',
    titleKey: 'catalog.event.childLostMittens.title',
    summaryKey: 'catalog.event.childLostMittens.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_class_pet_toy',
    titleKey: 'catalog.event.childClassPetToy.title',
    summaryKey: 'catalog.event.childClassPetToy.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_birthday_wish',
    titleKey: 'catalog.event.childBirthdayWish.title',
    summaryKey: 'catalog.event.childBirthdayWish.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_sidewalk_chalk',
    titleKey: 'catalog.event.childSidewalkChalk.title',
    summaryKey: 'catalog.event.childSidewalkChalk.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_first_bike',
    titleKey: 'catalog.event.childFirstBike.title',
    summaryKey: 'catalog.event.childFirstBike.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_blanket_fort',
    titleKey: 'catalog.event.childBlanketFort.title',
    summaryKey: 'catalog.event.childBlanketFort.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_kind_neighbor',
    titleKey: 'catalog.event.childKindNeighbor.title',
    summaryKey: 'catalog.event.childKindNeighbor.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_dentist_visit',
    titleKey: 'catalog.event.childDentistVisit.title',
    summaryKey: 'catalog.event.childDentistVisit.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_treehouse_dream',
    titleKey: 'catalog.event.childTreehouseDream.title',
    summaryKey: 'catalog.event.childTreehouseDream.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_goldfish_drawing',
    titleKey: 'catalog.event.childGoldfishDrawing.title',
    summaryKey: 'catalog.event.childGoldfishDrawing.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_rainy_puzzle',
    titleKey: 'catalog.event.childRainyPuzzle.title',
    summaryKey: 'catalog.event.childRainyPuzzle.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_pocket_coin',
    titleKey: 'catalog.event.childPocketCoin.title',
    summaryKey: 'catalog.event.childPocketCoin.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_playground_fall',
    titleKey: 'catalog.event.childPlaygroundFall.title',
    summaryKey: 'catalog.event.childPlaygroundFall.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: -1, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_museum_trip',
    titleKey: 'catalog.event.childMuseumTrip.title',
    summaryKey: 'catalog.event.childMuseumTrip.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_science_toy',
    titleKey: 'catalog.event.childScienceToy.title',
    summaryKey: 'catalog.event.childScienceToy.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_new_shoes',
    titleKey: 'catalog.event.childNewShoes.title',
    summaryKey: 'catalog.event.childNewShoes.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_sibling_tease',
    titleKey: 'catalog.event.childSiblingTease.title',
    summaryKey: 'catalog.event.childSiblingTease.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: -1, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_family_errand',
    titleKey: 'catalog.event.childFamilyErrand.title',
    summaryKey: 'catalog.event.childFamilyErrand.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_campfire_story',
    titleKey: 'catalog.event.childCampfireStory.title',
    summaryKey: 'catalog.event.childCampfireStory.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_quiet_library',
    titleKey: 'catalog.event.childQuietLibrary.title',
    summaryKey: 'catalog.event.childQuietLibrary.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_school_bus_friend',
    titleKey: 'catalog.event.childSchoolBusFriend.title',
    summaryKey: 'catalog.event.childSchoolBusFriend.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_garden_worms',
    titleKey: 'catalog.event.childGardenWorms.title',
    summaryKey: 'catalog.event.childGardenWorms.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_doctor_sticker',
    titleKey: 'catalog.event.childDoctorSticker.title',
    summaryKey: 'catalog.event.childDoctorSticker.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_handmade_card',
    titleKey: 'catalog.event.childHandmadeCard.title',
    summaryKey: 'catalog.event.childHandmadeCard.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_snow_day',
    titleKey: 'catalog.event.childSnowDay.title',
    summaryKey: 'catalog.event.childSnowDay.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_summer_swim',
    titleKey: 'catalog.event.childSummerSwim.title',
    summaryKey: 'catalog.event.childSummerSwim.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_broken_toy',
    titleKey: 'catalog.event.childBrokenToy.title',
    summaryKey: 'catalog.event.childBrokenToy.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: -1, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_brave_apology',
    titleKey: 'catalog.event.childBraveApology.title',
    summaryKey: 'catalog.event.childBraveApology.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_neighborhood_game',
    titleKey: 'catalog.event.childNeighborhoodGame.title',
    summaryKey: 'catalog.event.childNeighborhoodGame.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_grandparent_story',
    titleKey: 'catalog.event.childGrandparentStory.title',
    summaryKey: 'catalog.event.childGrandparentStory.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_first_allowance',
    titleKey: 'catalog.event.childFirstAllowance.title',
    summaryKey: 'catalog.event.childFirstAllowance.summary',
    stage: 'child',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_lost_ball',
    titleKey: 'catalog.event.childLostBall.title',
    summaryKey: 'catalog.event.childLostBall.summary',
    stage: 'child',
    weight: 2,
    effects: { attributes: { happiness: -1, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_nature_center',
    titleKey: 'catalog.event.childNatureCenter.title',
    summaryKey: 'catalog.event.childNatureCenter.summary',
    stage: 'child',
    weight: 3,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.child_night_light',
    titleKey: 'catalog.event.childNightLight.title',
    summaryKey: 'catalog.event.childNightLight.summary',
    stage: 'child',
    weight: 4,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Events/Childhood events', sourcePage: 'Events/Childhood events' }],
  },
  {
    id: 'p1_event.school_pop_quiz',
    titleKey: 'catalog.event.schoolPopQuiz.title',
    summaryKey: 'catalog.event.schoolPopQuiz.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 1, happiness: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_science_fair',
    titleKey: 'catalog.event.schoolScienceFair.title',
    summaryKey: 'catalog.event.schoolScienceFair.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_debate_club',
    titleKey: 'catalog.event.schoolDebateClub.title',
    summaryKey: 'catalog.event.schoolDebateClub.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_art_contest',
    titleKey: 'catalog.event.schoolArtContest.title',
    summaryKey: 'catalog.event.schoolArtContest.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 1, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_music_recital',
    titleKey: 'catalog.event.schoolMusicRecital.title',
    summaryKey: 'catalog.event.schoolMusicRecital.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_sports_tryout',
    titleKey: 'catalog.event.schoolSportsTryout.title',
    summaryKey: 'catalog.event.schoolSportsTryout.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_late_bus',
    titleKey: 'catalog.event.schoolLateBus.title',
    summaryKey: 'catalog.event.schoolLateBus.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_locker_jam',
    titleKey: 'catalog.event.schoolLockerJam.title',
    summaryKey: 'catalog.event.schoolLockerJam.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_teacher_meeting',
    titleKey: 'catalog.event.schoolTeacherMeeting.title',
    summaryKey: 'catalog.event.schoolTeacherMeeting.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_homework_stack',
    titleKey: 'catalog.event.schoolHomeworkStack.title',
    summaryKey: 'catalog.event.schoolHomeworkStack.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 1, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_exam_week',
    titleKey: 'catalog.event.schoolExamWeek.title',
    summaryKey: 'catalog.event.schoolExamWeek.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_field_trip',
    titleKey: 'catalog.event.schoolFieldTrip.title',
    summaryKey: 'catalog.event.schoolFieldTrip.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_cafeteria_seat',
    titleKey: 'catalog.event.schoolCafeteriaSeat.title',
    summaryKey: 'catalog.event.schoolCafeteriaSeat.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 1, happiness: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_partner_project',
    titleKey: 'catalog.event.schoolPartnerProject.title',
    summaryKey: 'catalog.event.schoolPartnerProject.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_library_fine',
    titleKey: 'catalog.event.schoolLibraryFine.title',
    summaryKey: 'catalog.event.schoolLibraryFine.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_spelling_bee',
    titleKey: 'catalog.event.schoolSpellingBee.title',
    summaryKey: 'catalog.event.schoolSpellingBee.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 1, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_math_challenge',
    titleKey: 'catalog.event.schoolMathChallenge.title',
    summaryKey: 'catalog.event.schoolMathChallenge.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_new_uniform',
    titleKey: 'catalog.event.schoolNewUniform.title',
    summaryKey: 'catalog.event.schoolNewUniform.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_nurse_visit',
    titleKey: 'catalog.event.schoolNurseVisit.title',
    summaryKey: 'catalog.event.schoolNurseVisit.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 1, happiness: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_student_council',
    titleKey: 'catalog.event.schoolStudentCouncil.title',
    summaryKey: 'catalog.event.schoolStudentCouncil.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_detention_warning',
    titleKey: 'catalog.event.schoolDetentionWarning.title',
    summaryKey: 'catalog.event.schoolDetentionWarning.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_favorite_teacher',
    titleKey: 'catalog.event.schoolFavoriteTeacher.title',
    summaryKey: 'catalog.event.schoolFavoriteTeacher.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 1, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_graduation_photo',
    titleKey: 'catalog.event.schoolGraduationPhoto.title',
    summaryKey: 'catalog.event.schoolGraduationPhoto.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_college_talk',
    titleKey: 'catalog.event.schoolCollegeTalk.title',
    summaryKey: 'catalog.event.schoolCollegeTalk.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_scholarship_form',
    titleKey: 'catalog.event.schoolScholarshipForm.title',
    summaryKey: 'catalog.event.schoolScholarshipForm.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 1, happiness: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_part_time_job',
    titleKey: 'catalog.event.schoolPartTimeJob.title',
    summaryKey: 'catalog.event.schoolPartTimeJob.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_club_election',
    titleKey: 'catalog.event.schoolClubElection.title',
    summaryKey: 'catalog.event.schoolClubElection.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_lab_mistake',
    titleKey: 'catalog.event.schoolLabMistake.title',
    summaryKey: 'catalog.event.schoolLabMistake.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_history_presentation',
    titleKey: 'catalog.event.schoolHistoryPresentation.title',
    summaryKey: 'catalog.event.schoolHistoryPresentation.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_language_exchange',
    titleKey: 'catalog.event.schoolLanguageExchange.title',
    summaryKey: 'catalog.event.schoolLanguageExchange.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 3, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_peer_tutor',
    titleKey: 'catalog.event.schoolPeerTutor.title',
    summaryKey: 'catalog.event.schoolPeerTutor.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 1, happiness: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_career_day',
    titleKey: 'catalog.event.schoolCareerDay.title',
    summaryKey: 'catalog.event.schoolCareerDay.summary',
    stage: 'school',
    weight: 5,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_lost_notebook',
    titleKey: 'catalog.event.schoolLostNotebook.title',
    summaryKey: 'catalog.event.schoolLostNotebook.summary',
    stage: 'school',
    weight: 2,
    effects: { attributes: { smarts: 1, happiness: -2 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_rainy_recess',
    titleKey: 'catalog.event.schoolRainyRecess.title',
    summaryKey: 'catalog.event.schoolRainyRecess.summary',
    stage: 'school',
    weight: 3,
    effects: { attributes: { smarts: 1, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.school_yearbook_page',
    titleKey: 'catalog.event.schoolYearbookPage.title',
    summaryKey: 'catalog.event.schoolYearbookPage.summary',
    stage: 'school',
    weight: 4,
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Education/Faculty Staff', sourcePage: 'Education/Faculty Staff' }],
  },
  {
    id: 'p1_event.adult_apartment_leak',
    titleKey: 'catalog.event.adultApartmentLeak.title',
    summaryKey: 'catalog.event.adultApartmentLeak.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: -2, health: -1 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_rent_increase',
    titleKey: 'catalog.event.adultRentIncrease.title',
    summaryKey: 'catalog.event.adultRentIncrease.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -270 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_job_interview',
    titleKey: 'catalog.event.adultJobInterview.title',
    summaryKey: 'catalog.event.adultJobInterview.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_office_birthday',
    titleKey: 'catalog.event.adultOfficeBirthday.title',
    summaryKey: 'catalog.event.adultOfficeBirthday.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_project_praise',
    titleKey: 'catalog.event.adultProjectPraise.title',
    summaryKey: 'catalog.event.adultProjectPraise.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_missed_deadline',
    titleKey: 'catalog.event.adultMissedDeadline.title',
    summaryKey: 'catalog.event.adultMissedDeadline.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_commute_kindness',
    titleKey: 'catalog.event.adultCommuteKindness.title',
    summaryKey: 'catalog.event.adultCommuteKindness.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_tax_season',
    titleKey: 'catalog.event.adultTaxSeason.title',
    summaryKey: 'catalog.event.adultTaxSeason.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: -2 }, money: -390 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_gym_routine',
    titleKey: 'catalog.event.adultGymRoutine.title',
    summaryKey: 'catalog.event.adultGymRoutine.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.adult_cooking_class',
    titleKey: 'catalog.event.adultCookingClass.title',
    summaryKey: 'catalog.event.adultCookingClass.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_first_car_repair',
    titleKey: 'catalog.event.adultFirstCarRepair.title',
    summaryKey: 'catalog.event.adultFirstCarRepair.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: -2, health: -1 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_savings_plan',
    titleKey: 'catalog.event.adultSavingsPlan.title',
    summaryKey: 'catalog.event.adultSavingsPlan.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_dental_checkup',
    titleKey: 'catalog.event.adultDentalCheckup.title',
    summaryKey: 'catalog.event.adultDentalCheckup.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.adult_old_friend_wedding',
    titleKey: 'catalog.event.adultOldFriendWedding.title',
    summaryKey: 'catalog.event.adultOldFriendWedding.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_dating_app_match',
    titleKey: 'catalog.event.adultDatingAppMatch.title',
    summaryKey: 'catalog.event.adultDatingAppMatch.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_family_emergency',
    titleKey: 'catalog.event.adultFamilyEmergency.title',
    summaryKey: 'catalog.event.adultFamilyEmergency.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: -2 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_new_neighbor',
    titleKey: 'catalog.event.adultNewNeighbor.title',
    summaryKey: 'catalog.event.adultNewNeighbor.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_home_inspection',
    titleKey: 'catalog.event.adultHomeInspection.title',
    summaryKey: 'catalog.event.adultHomeInspection.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_car_insurance',
    titleKey: 'catalog.event.adultCarInsurance.title',
    summaryKey: 'catalog.event.adultCarInsurance.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: -2, health: -1 }, money: -510 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_small_investment',
    titleKey: 'catalog.event.adultSmallInvestment.title',
    summaryKey: 'catalog.event.adultSmallInvestment.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_promotion_rumor',
    titleKey: 'catalog.event.adultPromotionRumor.title',
    summaryKey: 'catalog.event.adultPromotionRumor.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_work_conference',
    titleKey: 'catalog.event.adultWorkConference.title',
    summaryKey: 'catalog.event.adultWorkConference.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_mentor_lunch',
    titleKey: 'catalog.event.adultMentorLunch.title',
    summaryKey: 'catalog.event.adultMentorLunch.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Careers', sourcePage: 'Careers' }],
  },
  {
    id: 'p1_event.adult_side_gig',
    titleKey: 'catalog.event.adultSideGig.title',
    summaryKey: 'catalog.event.adultSideGig.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_plant_care',
    titleKey: 'catalog.event.adultPlantCare.title',
    summaryKey: 'catalog.event.adultPlantCare.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_medical_bill',
    titleKey: 'catalog.event.adultMedicalBill.title',
    summaryKey: 'catalog.event.adultMedicalBill.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.adult_vacation_deal',
    titleKey: 'catalog.event.adultVacationDeal.title',
    summaryKey: 'catalog.event.adultVacationDeal.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_lost_wallet',
    titleKey: 'catalog.event.adultLostWallet.title',
    summaryKey: 'catalog.event.adultLostWallet.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: -2 }, money: -390 },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_volunteer_day',
    titleKey: 'catalog.event.adultVolunteerDay.title',
    summaryKey: 'catalog.event.adultVolunteerDay.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_jury_summons',
    titleKey: 'catalog.event.adultJurySummons.title',
    summaryKey: 'catalog.event.adultJurySummons.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -630, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Crime', sourcePage: 'Crime' }],
  },
  {
    id: 'p1_event.adult_night_class',
    titleKey: 'catalog.event.adultNightClass.title',
    summaryKey: 'catalog.event.adultNightClass.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 1, health: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_public_speech',
    titleKey: 'catalog.event.adultPublicSpeech.title',
    summaryKey: 'catalog.event.adultPublicSpeech.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_housewarming',
    titleKey: 'catalog.event.adultHousewarming.title',
    summaryKey: 'catalog.event.adultHousewarming.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_broken_appliance',
    titleKey: 'catalog.event.adultBrokenAppliance.title',
    summaryKey: 'catalog.event.adultBrokenAppliance.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -510 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_credit_offer',
    titleKey: 'catalog.event.adultCreditOffer.title',
    summaryKey: 'catalog.event.adultCreditOffer.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_market_crash',
    titleKey: 'catalog.event.adultMarketCrash.title',
    summaryKey: 'catalog.event.adultMarketCrash.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: -2 }, money: -150 },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.adult_baby_news',
    titleKey: 'catalog.event.adultBabyNews.title',
    summaryKey: 'catalog.event.adultBabyNews.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 1, smarts: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_anniversary_dinner',
    titleKey: 'catalog.event.adultAnniversaryDinner.title',
    summaryKey: 'catalog.event.adultAnniversaryDinner.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_friend_needs_help',
    titleKey: 'catalog.event.adultFriendNeedsHelp.title',
    summaryKey: 'catalog.event.adultFriendNeedsHelp.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.adult_healthy_meal_prep',
    titleKey: 'catalog.event.adultHealthyMealPrep.title',
    summaryKey: 'catalog.event.adultHealthyMealPrep.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.adult_clinic_follow_up',
    titleKey: 'catalog.event.adultClinicFollowUp.title',
    summaryKey: 'catalog.event.adultClinicFollowUp.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 2, smarts: 1, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.adult_road_trip_delay',
    titleKey: 'catalog.event.adultRoadTripDelay.title',
    summaryKey: 'catalog.event.adultRoadTripDelay.summary',
    stage: 'adult',
    weight: 3,
    effects: { attributes: { happiness: -2 }, money: -270 },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_online_course',
    titleKey: 'catalog.event.adultOnlineCourse.title',
    summaryKey: 'catalog.event.adultOnlineCourse.summary',
    stage: 'adult',
    weight: 4,
    effects: { attributes: { happiness: 1 }, money: 250 },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_charity_run',
    titleKey: 'catalog.event.adultCharityRun.title',
    summaryKey: 'catalog.event.adultCharityRun.summary',
    stage: 'adult',
    weight: 5,
    effects: { attributes: { happiness: 2 }, addStatus: 'civic' },
    sourceRefs: [{ sourceTitle: 'Activities', sourcePage: 'Activities' }],
  },
  {
    id: 'p1_event.adult_unexpected_refund',
    titleKey: 'catalog.event.adultUnexpectedRefund.title',
    summaryKey: 'catalog.event.adultUnexpectedRefund.summary',
    stage: 'adult',
    weight: 2,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Assets', sourcePage: 'Assets' }],
  },
  {
    id: 'p1_event.elder_morning_stretch',
    titleKey: 'catalog.event.elderMorningStretch.title',
    summaryKey: 'catalog.event.elderMorningStretch.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 2, health: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_grandchild_visit',
    titleKey: 'catalog.event.elderGrandchildVisit.title',
    summaryKey: 'catalog.event.elderGrandchildVisit.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_pension_letter',
    titleKey: 'catalog.event.elderPensionLetter.title',
    summaryKey: 'catalog.event.elderPensionLetter.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_garden_harvest',
    titleKey: 'catalog.event.elderGardenHarvest.title',
    summaryKey: 'catalog.event.elderGardenHarvest.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_doctor_followup',
    titleKey: 'catalog.event.elderDoctorFollowup.title',
    summaryKey: 'catalog.event.elderDoctorFollowup.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 3, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.elder_old_coworker_call',
    titleKey: 'catalog.event.elderOldCoworkerCall.title',
    summaryKey: 'catalog.event.elderOldCoworkerCall.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 4, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_community_class',
    titleKey: 'catalog.event.elderCommunityClass.title',
    summaryKey: 'catalog.event.elderCommunityClass.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_downsizing_talk',
    titleKey: 'catalog.event.elderDownsizingTalk.title',
    summaryKey: 'catalog.event.elderDownsizingTalk.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_photo_digitizing',
    titleKey: 'catalog.event.elderPhotoDigitizing.title',
    summaryKey: 'catalog.event.elderPhotoDigitizing.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 4, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_gentle_swim',
    titleKey: 'catalog.event.elderGentleSwim.title',
    summaryKey: 'catalog.event.elderGentleSwim.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_medication_review',
    titleKey: 'catalog.event.elderMedicationReview.title',
    summaryKey: 'catalog.event.elderMedicationReview.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.elder_neighbor_checks_in',
    titleKey: 'catalog.event.elderNeighborChecksIn.title',
    summaryKey: 'catalog.event.elderNeighborChecksIn.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_quiet_birthday',
    titleKey: 'catalog.event.elderQuietBirthday.title',
    summaryKey: 'catalog.event.elderQuietBirthday.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 2, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_estate_planning',
    titleKey: 'catalog.event.elderEstatePlanning.title',
    summaryKey: 'catalog.event.elderEstatePlanning.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 3 }, addStatus: 'has_will' },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_memory_slip',
    titleKey: 'catalog.event.elderMemorySlip.title',
    summaryKey: 'catalog.event.elderMemorySlip.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: -2, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_hearing_aid',
    titleKey: 'catalog.event.elderHearingAid.title',
    summaryKey: 'catalog.event.elderHearingAid.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Medical Doctor', sourcePage: 'Medical Doctor' }],
  },
  {
    id: 'p1_event.elder_park_bench_chat',
    titleKey: 'catalog.event.elderParkBenchChat.title',
    summaryKey: 'catalog.event.elderParkBenchChat.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 3, health: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_family_recipe',
    titleKey: 'catalog.event.elderFamilyRecipe.title',
    summaryKey: 'catalog.event.elderFamilyRecipe.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_old_friend_farewell',
    titleKey: 'catalog.event.elderOldFriendFarewell.title',
    summaryKey: 'catalog.event.elderOldFriendFarewell.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: -2, health: -1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_senior_discount',
    titleKey: 'catalog.event.elderSeniorDiscount.title',
    summaryKey: 'catalog.event.elderSeniorDiscount.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_volunteer_reading',
    titleKey: 'catalog.event.elderVolunteerReading.title',
    summaryKey: 'catalog.event.elderVolunteerReading.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 4, health: 1, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_chair_exercise',
    titleKey: 'catalog.event.elderChairExercise.title',
    summaryKey: 'catalog.event.elderChairExercise.summary',
    stage: 'elder',
    weight: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_long_nap',
    titleKey: 'catalog.event.elderLongNap.title',
    summaryKey: 'catalog.event.elderLongNap.summary',
    stage: 'elder',
    weight: 4,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_window_light',
    titleKey: 'catalog.event.elderWindowLight.title',
    summaryKey: 'catalog.event.elderWindowLight.summary',
    stage: 'elder',
    weight: 5,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
  {
    id: 'p1_event.elder_legacy_letter',
    titleKey: 'catalog.event.elderLegacyLetter.title',
    summaryKey: 'catalog.event.elderLegacyLetter.summary',
    stage: 'elder',
    weight: 2,
    effects: { attributes: { happiness: 2, health: 1 }, addStatus: 'has_will' },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships' }],
  },
];
