import type { CatalogItem, EffectConfig } from '../schema/catalogTypes';

export type PrisonActivityRisk = 'low' | 'medium' | 'high';

export interface PrisonActivityCatalogItem extends CatalogItem {
  risk: PrisonActivityRisk;
  effects: EffectConfig;
}

const prisonActivitiesSource = { sourceTitle: 'Prison/Activities', sourcePage: 'Prison/Activities' };

export const prisonActivities: PrisonActivityCatalogItem[] = [
  {
    id: 'prison.appeal',
    titleKey: 'catalog.prison.appeal.title',
    summaryKey: 'catalog.prison.appeal.summary',
    risk: 'medium',
    effects: { money: -1500 },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.prison_yard',
    titleKey: 'catalog.prison.prisonYard.title',
    summaryKey: 'catalog.prison.prisonYard.summary',
    risk: 'low',
    effects: { attributes: { health: 2, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.escape',
    titleKey: 'catalog.prison.escape.title',
    summaryKey: 'catalog.prison.escape.summary',
    risk: 'high',
    effects: { attributes: { happiness: -6 }, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.library_shift',
    titleKey: 'catalog.prison.libraryShift.title',
    summaryKey: 'catalog.prison.libraryShift.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.kitchen_duty',
    titleKey: 'catalog.prison.kitchenDuty.title',
    summaryKey: 'catalog.prison.kitchenDuty.summary',
    risk: 'low',
    effects: { attributes: { health: 1, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.laundry_detail',
    titleKey: 'catalog.prison.laundryDetail.title',
    summaryKey: 'catalog.prison.laundryDetail.summary',
    risk: 'low',
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.chapel_service',
    titleKey: 'catalog.prison.chapelService.title',
    summaryKey: 'catalog.prison.chapelService.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.exercise_block',
    titleKey: 'catalog.prison.exerciseBlock.title',
    summaryKey: 'catalog.prison.exerciseBlock.summary',
    risk: 'medium',
    effects: { attributes: { health: 3, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.study_group',
    titleKey: 'catalog.prison.studyGroup.title',
    summaryKey: 'catalog.prison.studyGroup.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.legal_research',
    titleKey: 'catalog.prison.legalResearch.title',
    summaryKey: 'catalog.prison.legalResearch.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2, happiness: -1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.counseling_session',
    titleKey: 'catalog.prison.counselingSession.title',
    summaryKey: 'catalog.prison.counselingSession.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.art_class',
    titleKey: 'catalog.prison.artClass.title',
    summaryKey: 'catalog.prison.artClass.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2, looks: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.music_hour',
    titleKey: 'catalog.prison.musicHour.title',
    summaryKey: 'catalog.prison.musicHour.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.chess_match',
    titleKey: 'catalog.prison.chessMatch.title',
    summaryKey: 'catalog.prison.chessMatch.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.letter_home',
    titleKey: 'catalog.prison.letterHome.title',
    summaryKey: 'catalog.prison.letterHome.summary',
    risk: 'low',
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.meditation_circle',
    titleKey: 'catalog.prison.meditationCircle.title',
    summaryKey: 'catalog.prison.meditationCircle.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2, health: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.garden_detail',
    titleKey: 'catalog.prison.gardenDetail.title',
    summaryKey: 'catalog.prison.gardenDetail.summary',
    risk: 'low',
    effects: { attributes: { health: 1, happiness: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.mentor_newcomer',
    titleKey: 'catalog.prison.mentorNewcomer.title',
    summaryKey: 'catalog.prison.mentorNewcomer.summary',
    risk: 'medium',
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.clean_cell',
    titleKey: 'catalog.prison.cleanCell.title',
    summaryKey: 'catalog.prison.cleanCell.summary',
    risk: 'low',
    effects: { attributes: { health: 1, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.workshop_shift',
    titleKey: 'catalog.prison.workshopShift.title',
    summaryKey: 'catalog.prison.workshopShift.summary',
    risk: 'medium',
    effects: { attributes: { smarts: 1, happiness: 1 }, money: 25 },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.job_training',
    titleKey: 'catalog.prison.jobTraining.title',
    summaryKey: 'catalog.prison.jobTraining.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.parole_prep',
    titleKey: 'catalog.prison.parolePrep.title',
    summaryKey: 'catalog.prison.parolePrep.summary',
    risk: 'low',
    effects: { attributes: { smarts: 1, happiness: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.apology_letter',
    titleKey: 'catalog.prison.apologyLetter.title',
    summaryKey: 'catalog.prison.apologyLetter.summary',
    risk: 'low',
    effects: { attributes: { happiness: 1, smarts: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.guard_conversation',
    titleKey: 'catalog.prison.guardConversation.title',
    summaryKey: 'catalog.prison.guardConversation.summary',
    risk: 'medium',
    effects: { attributes: { happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.contraband_search',
    titleKey: 'catalog.prison.contrabandSearch.title',
    summaryKey: 'catalog.prison.contrabandSearch.summary',
    risk: 'medium',
    effects: { attributes: { happiness: -2 }, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.yard_argument',
    titleKey: 'catalog.prison.yardArgument.title',
    summaryKey: 'catalog.prison.yardArgument.summary',
    risk: 'medium',
    effects: { attributes: { happiness: -2, health: -1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.gang_pressure',
    titleKey: 'catalog.prison.gangPressure.title',
    summaryKey: 'catalog.prison.gangPressure.summary',
    risk: 'high',
    effects: { attributes: { happiness: -4, health: -2 }, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.protection_deal',
    titleKey: 'catalog.prison.protectionDeal.title',
    summaryKey: 'catalog.prison.protectionDeal.summary',
    risk: 'high',
    effects: { attributes: { happiness: -2 }, money: -200, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.gambling_circle',
    titleKey: 'catalog.prison.gamblingCircle.title',
    summaryKey: 'catalog.prison.gamblingCircle.summary',
    risk: 'medium',
    effects: { attributes: { happiness: 1 }, money: -120, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.black_market_trade',
    titleKey: 'catalog.prison.blackMarketTrade.title',
    summaryKey: 'catalog.prison.blackMarketTrade.summary',
    risk: 'high',
    effects: { attributes: { happiness: 1 }, money: 150, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.cell_block_fight',
    titleKey: 'catalog.prison.cellBlockFight.title',
    summaryKey: 'catalog.prison.cellBlockFight.summary',
    risk: 'high',
    effects: { attributes: { health: -6, happiness: -4 }, addStatus: 'injured' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.escape_tunnel',
    titleKey: 'catalog.prison.escapeTunnel.title',
    summaryKey: 'catalog.prison.escapeTunnel.summary',
    risk: 'high',
    effects: { attributes: { smarts: 1, happiness: -5 }, money: -300, addStatus: 'suspicious' },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.hunger_strike',
    titleKey: 'catalog.prison.hungerStrike.title',
    summaryKey: 'catalog.prison.hungerStrike.summary',
    risk: 'high',
    effects: { attributes: { health: -5, happiness: -1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.solitary_reflection',
    titleKey: 'catalog.prison.solitaryReflection.title',
    summaryKey: 'catalog.prison.solitaryReflection.summary',
    risk: 'medium',
    effects: { attributes: { happiness: -3, smarts: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.rumor_control',
    titleKey: 'catalog.prison.rumorControl.title',
    summaryKey: 'catalog.prison.rumorControl.summary',
    risk: 'medium',
    effects: { attributes: { smarts: 1, happiness: -1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.book_club',
    titleKey: 'catalog.prison.bookClub.title',
    summaryKey: 'catalog.prison.bookClub.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2, happiness: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.basic_math_class',
    titleKey: 'catalog.prison.basicMathClass.title',
    summaryKey: 'catalog.prison.basicMathClass.summary',
    risk: 'low',
    effects: { attributes: { smarts: 2 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.anger_management',
    titleKey: 'catalog.prison.angerManagement.title',
    summaryKey: 'catalog.prison.angerManagement.summary',
    risk: 'low',
    effects: { attributes: { happiness: 2, health: 1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.medical_line',
    titleKey: 'catalog.prison.medicalLine.title',
    summaryKey: 'catalog.prison.medicalLine.summary',
    risk: 'low',
    effects: { attributes: { health: 2, happiness: -1 } },
    sourceRefs: [prisonActivitiesSource],
  },
  {
    id: 'prison.family_visit_room',
    titleKey: 'catalog.prison.familyVisitRoom.title',
    summaryKey: 'catalog.prison.familyVisitRoom.summary',
    risk: 'low',
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [prisonActivitiesSource],
  },
];
