import type { CatalogItem, EffectConfig } from '../schema/catalogTypes';

export type RelationshipEventType = 'family' | 'friend' | 'romance';

export interface RelationshipEventCatalogItem extends CatalogItem {
  type: RelationshipEventType;
  minAge: number;
  effects: EffectConfig;
}

const relationshipsSource = { sourceTitle: 'Relationships', sourcePage: 'Relationships' };

export const relationshipEventConfigs: RelationshipEventCatalogItem[] = [
  {
    id: 'relationship.family_time',
    titleKey: 'catalog.relationship.familyTime.title',
    summaryKey: 'catalog.relationship.familyTime.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships', sourceSection: 'Spend Time' }],
  },
  {
    id: 'relationship.make_friend',
    titleKey: 'catalog.relationship.makeFriend.title',
    summaryKey: 'catalog.relationship.makeFriend.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [{ sourceTitle: 'Relationships', sourcePage: 'Relationships', sourceSection: 'Friends' }],
  },
  {
    id: 'relationship.first_date',
    titleKey: 'catalog.relationship.firstDate.title',
    summaryKey: 'catalog.relationship.firstDate.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [{ sourceTitle: 'Dating App', sourcePage: 'Dating App' }],
  },
  {
    id: 'relationship.family_game_night',
    titleKey: 'catalog.relationship.familyGameNight.title',
    summaryKey: 'catalog.relationship.familyGameNight.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.sibling_errand',
    titleKey: 'catalog.relationship.siblingErrand.title',
    summaryKey: 'catalog.relationship.siblingErrand.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.parent_call',
    titleKey: 'catalog.relationship.parentCall.title',
    summaryKey: 'catalog.relationship.parentCall.summary',
    type: 'family',
    minAge: 7,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.cousin_visit',
    titleKey: 'catalog.relationship.cousinVisit.title',
    summaryKey: 'catalog.relationship.cousinVisit.summary',
    type: 'family',
    minAge: 9,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_recipe',
    titleKey: 'catalog.relationship.familyRecipe.title',
    summaryKey: 'catalog.relationship.familyRecipe.summary',
    type: 'family',
    minAge: 11,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.holiday_dinner',
    titleKey: 'catalog.relationship.holidayDinner.title',
    summaryKey: 'catalog.relationship.holidayDinner.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_photo',
    titleKey: 'catalog.relationship.familyPhoto.title',
    summaryKey: 'catalog.relationship.familyPhoto.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.hospital_visit',
    titleKey: 'catalog.relationship.hospitalVisit.title',
    summaryKey: 'catalog.relationship.hospitalVisit.summary',
    type: 'family',
    minAge: 7,
    effects: { attributes: { happiness: 5, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_apology',
    titleKey: 'catalog.relationship.familyApology.title',
    summaryKey: 'catalog.relationship.familyApology.summary',
    type: 'family',
    minAge: 9,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.bedtime_story',
    titleKey: 'catalog.relationship.bedtimeStory.title',
    summaryKey: 'catalog.relationship.bedtimeStory.summary',
    type: 'family',
    minAge: 11,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_budget_talk',
    titleKey: 'catalog.relationship.familyBudgetTalk.title',
    summaryKey: 'catalog.relationship.familyBudgetTalk.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.parent_advice',
    titleKey: 'catalog.relationship.parentAdvice.title',
    summaryKey: 'catalog.relationship.parentAdvice.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.sibling_secret',
    titleKey: 'catalog.relationship.siblingSecret.title',
    summaryKey: 'catalog.relationship.siblingSecret.summary',
    type: 'family',
    minAge: 7,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_picnic',
    titleKey: 'catalog.relationship.familyPicnic.title',
    summaryKey: 'catalog.relationship.familyPicnic.summary',
    type: 'family',
    minAge: 9,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.home_repair',
    titleKey: 'catalog.relationship.homeRepair.title',
    summaryKey: 'catalog.relationship.homeRepair.summary',
    type: 'family',
    minAge: 11,
    effects: { attributes: { happiness: 4, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_movie',
    titleKey: 'catalog.relationship.familyMovie.title',
    summaryKey: 'catalog.relationship.familyMovie.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.shared_chores',
    titleKey: 'catalog.relationship.sharedChores.title',
    summaryKey: 'catalog.relationship.sharedChores.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.grandparent_tea',
    titleKey: 'catalog.relationship.grandparentTea.title',
    summaryKey: 'catalog.relationship.grandparentTea.summary',
    type: 'family',
    minAge: 7,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.school_celebration',
    titleKey: 'catalog.relationship.schoolCelebration.title',
    summaryKey: 'catalog.relationship.schoolCelebration.summary',
    type: 'family',
    minAge: 9,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.baby_shower',
    titleKey: 'catalog.relationship.babyShower.title',
    summaryKey: 'catalog.relationship.babyShower.summary',
    type: 'family',
    minAge: 11,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_walk',
    titleKey: 'catalog.relationship.familyWalk.title',
    summaryKey: 'catalog.relationship.familyWalk.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.heirloom_talk',
    titleKey: 'catalog.relationship.heirloomTalk.title',
    summaryKey: 'catalog.relationship.heirloomTalk.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.birthday_call',
    titleKey: 'catalog.relationship.birthdayCall.title',
    summaryKey: 'catalog.relationship.birthdayCall.summary',
    type: 'family',
    minAge: 7,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_road_trip',
    titleKey: 'catalog.relationship.familyRoadTrip.title',
    summaryKey: 'catalog.relationship.familyRoadTrip.summary',
    type: 'family',
    minAge: 9,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_disagreement',
    titleKey: 'catalog.relationship.familyDisagreement.title',
    summaryKey: 'catalog.relationship.familyDisagreement.summary',
    type: 'family',
    minAge: 11,
    effects: { attributes: { happiness: -1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.care_package',
    titleKey: 'catalog.relationship.carePackage.title',
    summaryKey: 'catalog.relationship.carePackage.summary',
    type: 'family',
    minAge: 3,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.family_check_in',
    titleKey: 'catalog.relationship.familyCheckIn.title',
    summaryKey: 'catalog.relationship.familyCheckIn.summary',
    type: 'family',
    minAge: 5,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.playground_invite',
    titleKey: 'catalog.relationship.playgroundInvite.title',
    summaryKey: 'catalog.relationship.playgroundInvite.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 2, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.study_buddy',
    titleKey: 'catalog.relationship.studyBuddy.title',
    summaryKey: 'catalog.relationship.studyBuddy.summary',
    type: 'friend',
    minAge: 8,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.lunch_table',
    titleKey: 'catalog.relationship.lunchTable.title',
    summaryKey: 'catalog.relationship.lunchTable.summary',
    type: 'friend',
    minAge: 10,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.club_meetup',
    titleKey: 'catalog.relationship.clubMeetup.title',
    summaryKey: 'catalog.relationship.clubMeetup.summary',
    type: 'friend',
    minAge: 12,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.sports_practice',
    titleKey: 'catalog.relationship.sportsPractice.title',
    summaryKey: 'catalog.relationship.sportsPractice.summary',
    type: 'friend',
    minAge: 14,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.movie_invite',
    titleKey: 'catalog.relationship.movieInvite.title',
    summaryKey: 'catalog.relationship.movieInvite.summary',
    type: 'friend',
    minAge: 16,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.honest_advice',
    titleKey: 'catalog.relationship.honestAdvice.title',
    summaryKey: 'catalog.relationship.honestAdvice.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.birthday_party',
    titleKey: 'catalog.relationship.birthdayParty.title',
    summaryKey: 'catalog.relationship.birthdayParty.summary',
    type: 'friend',
    minAge: 8,
    effects: { attributes: { happiness: 5, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.friend_argument',
    titleKey: 'catalog.relationship.friendArgument.title',
    summaryKey: 'catalog.relationship.friendArgument.summary',
    type: 'friend',
    minAge: 10,
    effects: { attributes: { happiness: -1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.apology_text',
    titleKey: 'catalog.relationship.apologyText.title',
    summaryKey: 'catalog.relationship.apologyText.summary',
    type: 'friend',
    minAge: 12,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.group_chat',
    titleKey: 'catalog.relationship.groupChat.title',
    summaryKey: 'catalog.relationship.groupChat.summary',
    type: 'friend',
    minAge: 14,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.weekend_hike',
    titleKey: 'catalog.relationship.weekendHike.title',
    summaryKey: 'catalog.relationship.weekendHike.summary',
    type: 'friend',
    minAge: 16,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.cafe_catchup',
    titleKey: 'catalog.relationship.cafeCatchup.title',
    summaryKey: 'catalog.relationship.cafeCatchup.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.concert_night',
    titleKey: 'catalog.relationship.concertNight.title',
    summaryKey: 'catalog.relationship.concertNight.summary',
    type: 'friend',
    minAge: 8,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.moving_help',
    titleKey: 'catalog.relationship.movingHelp.title',
    summaryKey: 'catalog.relationship.movingHelp.summary',
    type: 'friend',
    minAge: 10,
    effects: { attributes: { happiness: 4, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.roommate_talk',
    titleKey: 'catalog.relationship.roommateTalk.title',
    summaryKey: 'catalog.relationship.roommateTalk.summary',
    type: 'friend',
    minAge: 12,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.borrowed_book',
    titleKey: 'catalog.relationship.borrowedBook.title',
    summaryKey: 'catalog.relationship.borrowedBook.summary',
    type: 'friend',
    minAge: 14,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.gaming_session',
    titleKey: 'catalog.relationship.gamingSession.title',
    summaryKey: 'catalog.relationship.gamingSession.summary',
    type: 'friend',
    minAge: 16,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.charity_shift',
    titleKey: 'catalog.relationship.charityShift.title',
    summaryKey: 'catalog.relationship.charityShift.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.gym_partner',
    titleKey: 'catalog.relationship.gymPartner.title',
    summaryKey: 'catalog.relationship.gymPartner.summary',
    type: 'friend',
    minAge: 8,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.road_trip_plan',
    titleKey: 'catalog.relationship.roadTripPlan.title',
    summaryKey: 'catalog.relationship.roadTripPlan.summary',
    type: 'friend',
    minAge: 10,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.career_referral',
    titleKey: 'catalog.relationship.careerReferral.title',
    summaryKey: 'catalog.relationship.careerReferral.summary',
    type: 'friend',
    minAge: 12,
    effects: { attributes: { happiness: 3, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.late_night_call',
    titleKey: 'catalog.relationship.lateNightCall.title',
    summaryKey: 'catalog.relationship.lateNightCall.summary',
    type: 'friend',
    minAge: 14,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.wedding_guest',
    titleKey: 'catalog.relationship.weddingGuest.title',
    summaryKey: 'catalog.relationship.weddingGuest.summary',
    type: 'friend',
    minAge: 16,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.friendship_boundary',
    titleKey: 'catalog.relationship.friendshipBoundary.title',
    summaryKey: 'catalog.relationship.friendshipBoundary.summary',
    type: 'friend',
    minAge: 6,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.crush_message',
    titleKey: 'catalog.relationship.crushMessage.title',
    summaryKey: 'catalog.relationship.crushMessage.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: 2, smarts: 1, looks: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.first_coffee',
    titleKey: 'catalog.relationship.firstCoffee.title',
    summaryKey: 'catalog.relationship.firstCoffee.summary',
    type: 'romance',
    minAge: 18,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.second_date',
    titleKey: 'catalog.relationship.secondDate.title',
    summaryKey: 'catalog.relationship.secondDate.summary',
    type: 'romance',
    minAge: 20,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.picnic_date',
    titleKey: 'catalog.relationship.picnicDate.title',
    summaryKey: 'catalog.relationship.picnicDate.summary',
    type: 'romance',
    minAge: 22,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.dinner_reservation',
    titleKey: 'catalog.relationship.dinnerReservation.title',
    summaryKey: 'catalog.relationship.dinnerReservation.summary',
    type: 'romance',
    minAge: 24,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.awkward_silence',
    titleKey: 'catalog.relationship.awkwardSilence.title',
    summaryKey: 'catalog.relationship.awkwardSilence.summary',
    type: 'romance',
    minAge: 26,
    effects: { attributes: { happiness: -2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.anniversary_plan',
    titleKey: 'catalog.relationship.anniversaryPlan.title',
    summaryKey: 'catalog.relationship.anniversaryPlan.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.meet_parents',
    titleKey: 'catalog.relationship.meetParents.title',
    summaryKey: 'catalog.relationship.meetParents.summary',
    type: 'romance',
    minAge: 18,
    effects: { attributes: { happiness: 5, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.shared_apartment_talk',
    titleKey: 'catalog.relationship.sharedApartmentTalk.title',
    summaryKey: 'catalog.relationship.sharedApartmentTalk.summary',
    type: 'romance',
    minAge: 20,
    effects: { attributes: { happiness: 2, looks: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.proposal_hint',
    titleKey: 'catalog.relationship.proposalHint.title',
    summaryKey: 'catalog.relationship.proposalHint.summary',
    type: 'romance',
    minAge: 22,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.wedding_planning',
    titleKey: 'catalog.relationship.weddingPlanning.title',
    summaryKey: 'catalog.relationship.weddingPlanning.summary',
    type: 'romance',
    minAge: 24,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.honeymoon_idea',
    titleKey: 'catalog.relationship.honeymoonIdea.title',
    summaryKey: 'catalog.relationship.honeymoonIdea.summary',
    type: 'romance',
    minAge: 26,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.jealousy_talk',
    titleKey: 'catalog.relationship.jealousyTalk.title',
    summaryKey: 'catalog.relationship.jealousyTalk.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: -1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.honest_confession',
    titleKey: 'catalog.relationship.honestConfession.title',
    summaryKey: 'catalog.relationship.honestConfession.summary',
    type: 'romance',
    minAge: 18,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.long_distance_call',
    titleKey: 'catalog.relationship.longDistanceCall.title',
    summaryKey: 'catalog.relationship.longDistanceCall.summary',
    type: 'romance',
    minAge: 20,
    effects: { attributes: { happiness: 4, smarts: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.couples_budget',
    titleKey: 'catalog.relationship.couplesBudget.title',
    summaryKey: 'catalog.relationship.couplesBudget.summary',
    type: 'romance',
    minAge: 22,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.partner_illness',
    titleKey: 'catalog.relationship.partnerIllness.title',
    summaryKey: 'catalog.relationship.partnerIllness.summary',
    type: 'romance',
    minAge: 24,
    effects: { attributes: { happiness: 2, looks: 1 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.quiet_morning',
    titleKey: 'catalog.relationship.quietMorning.title',
    summaryKey: 'catalog.relationship.quietMorning.summary',
    type: 'romance',
    minAge: 26,
    effects: { attributes: { happiness: 3 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.surprise_gift',
    titleKey: 'catalog.relationship.surpriseGift.title',
    summaryKey: 'catalog.relationship.surpriseGift.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.dance_night',
    titleKey: 'catalog.relationship.danceNight.title',
    summaryKey: 'catalog.relationship.danceNight.summary',
    type: 'romance',
    minAge: 18,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.future_children_talk',
    titleKey: 'catalog.relationship.futureChildrenTalk.title',
    summaryKey: 'catalog.relationship.futureChildrenTalk.summary',
    type: 'romance',
    minAge: 20,
    effects: { attributes: { happiness: 2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.breakup_conversation',
    titleKey: 'catalog.relationship.breakupConversation.title',
    summaryKey: 'catalog.relationship.breakupConversation.summary',
    type: 'romance',
    minAge: 22,
    effects: { attributes: { happiness: -2 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.reconciliation_dinner',
    titleKey: 'catalog.relationship.reconciliationDinner.title',
    summaryKey: 'catalog.relationship.reconciliationDinner.summary',
    type: 'romance',
    minAge: 24,
    effects: { attributes: { happiness: 4 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.retirement_together',
    titleKey: 'catalog.relationship.retirementTogether.title',
    summaryKey: 'catalog.relationship.retirementTogether.summary',
    type: 'romance',
    minAge: 26,
    effects: { attributes: { happiness: 5 } },
    sourceRefs: [relationshipsSource],
  },
  {
    id: 'relationship.memory_lane_walk',
    titleKey: 'catalog.relationship.memoryLaneWalk.title',
    summaryKey: 'catalog.relationship.memoryLaneWalk.summary',
    type: 'romance',
    minAge: 16,
    effects: { attributes: { happiness: 2, looks: 1 } },
    sourceRefs: [relationshipsSource],
  },
];
