import type { LifeEventOption } from '../game/types';

type ActivityEffects = LifeEventOption['effects'];

export interface ActivityConfig {
  id: string;
  titleKey: string;
  summaryKey: string;
  resultKey: string;
  minAge: number;
  cost: number;
  icon: string;
  oncePerAge?: boolean;
  effects: ActivityEffects;
}

export const activities: ActivityConfig[] = [
  {
    id: 'rest',
    titleKey: 'ui.action.rest',
    summaryKey: 'activity.rest.summary',
    resultKey: 'activity.rest.result',
    minAge: 0,
    cost: 0,
    icon: 'fluent-emoji-flat:sleeping-face',
    oncePerAge: true,
    effects: { attributes: { health: 6, happiness: 2 }, school: { stress: -6 } },
  },
  {
    id: 'study',
    titleKey: 'ui.action.study',
    summaryKey: 'activity.study.summary',
    resultKey: 'activity.study.result',
    minAge: 6,
    cost: 0,
    icon: 'fluent-emoji-flat:books',
    oncePerAge: true,
    effects: { attributes: { smarts: 5, happiness: -2 }, school: { stress: 5 } },
  },
  {
    id: 'family_time',
    titleKey: 'ui.action.familyTime',
    summaryKey: 'activity.familyTime.summary',
    resultKey: 'activity.familyTime.result',
    minAge: 0,
    cost: 0,
    icon: 'noto:family',
    effects: { attributes: { happiness: 4 }, relationship: { type: 'mother', closeness: 4 } },
  },
  {
    id: 'doctor_visit',
    titleKey: 'ui.action.doctorVisit',
    summaryKey: 'activity.doctorVisit.summary',
    resultKey: 'activity.doctorVisit.result',
    minAge: 0,
    cost: 200,
    icon: 'fluent-emoji-flat:man-health-worker',
    effects: { attributes: { health: 12 }, money: -200 },
  },
  {
    id: 'emergency_room',
    titleKey: 'ui.action.emergencyRoom',
    summaryKey: 'activity.emergencyRoom.summary',
    resultKey: 'activity.emergencyRoom.result',
    minAge: 4,
    cost: 300,
    icon: 'fluent-emoji-flat:hospital',
    effects: { attributes: { health: 16, happiness: -1 }, money: -300 },
  },
  {
    id: 'optometrist',
    titleKey: 'ui.action.optometrist',
    summaryKey: 'activity.optometrist.summary',
    resultKey: 'activity.optometrist.result',
    minAge: 4,
    cost: 120,
    icon: 'fluent-emoji-flat:glasses',
    effects: { attributes: { smarts: 1, health: 2 }, money: -120 },
  },
  {
    id: 'exercise',
    titleKey: 'ui.action.exercise',
    summaryKey: 'activity.exercise.summary',
    resultKey: 'activity.exercise.result',
    minAge: 6,
    cost: 0,
    icon: 'fluent-emoji-flat:person-running',
    effects: { attributes: { health: 4, happiness: 1 } },
  },
  {
    id: 'book',
    titleKey: 'ui.action.book',
    summaryKey: 'activity.book.summary',
    resultKey: 'activity.book.result',
    minAge: 6,
    cost: 0,
    icon: 'fluent-emoji-flat:open-book',
    effects: { attributes: { smarts: 4, happiness: 1 } },
  },
  {
    id: 'walk',
    titleKey: 'ui.action.walk',
    summaryKey: 'activity.walk.summary',
    resultKey: 'activity.walk.result',
    minAge: 8,
    cost: 0,
    icon: 'fluent-emoji-flat:person-walking',
    effects: { attributes: { health: 3, happiness: 2 }, school: { stress: -2 } },
  },
  {
    id: 'martial_arts',
    titleKey: 'ui.action.martialArts',
    summaryKey: 'activity.martialArts.summary',
    resultKey: 'activity.martialArts.result',
    minAge: 8,
    cost: 40,
    icon: 'fluent-emoji-flat:martial-arts-uniform',
    effects: { attributes: { health: 4, smarts: 1 }, money: -40 },
  },
  {
    id: 'identity',
    titleKey: 'ui.action.identity',
    summaryKey: 'activity.identity.summary',
    resultKey: 'activity.identity.result',
    minAge: 4,
    cost: 0,
    icon: 'fluent-emoji-flat:artist-palette',
    effects: { attributes: { happiness: 2, smarts: 1 } },
  },
  {
    id: 'accessories',
    titleKey: 'ui.action.accessories',
    summaryKey: 'activity.accessories.summary',
    resultKey: 'activity.accessories.result',
    minAge: 0,
    cost: 30,
    icon: 'fluent-emoji-flat:sunglasses',
    effects: { attributes: { looks: 2, happiness: 1 }, money: -30 },
  },
  {
    id: 'movie_theater',
    titleKey: 'ui.action.movieTheater',
    summaryKey: 'activity.movieTheater.summary',
    resultKey: 'activity.movieTheater.result',
    minAge: 6,
    cost: 15,
    icon: 'fluent-emoji-flat:film-frames',
    effects: { attributes: { happiness: 4 }, money: -15 },
  },
  {
    id: 'socialize',
    titleKey: 'ui.action.socialize',
    summaryKey: 'activity.socialize.summary',
    resultKey: 'activity.socialize.result',
    minAge: 13,
    cost: 20,
    icon: 'fluent-emoji-flat:party-popper',
    effects: { attributes: { happiness: 4 }, money: -20 },
  },
  {
    id: 'hobby_class',
    titleKey: 'ui.action.hobbyClass',
    summaryKey: 'activity.hobbyClass.summary',
    resultKey: 'activity.hobbyClass.result',
    minAge: 16,
    cost: 80,
    icon: 'fluent-emoji-flat:artist-palette',
    effects: { attributes: { happiness: 2, smarts: 2 }, money: -80 },
  },
  {
    id: 'library',
    titleKey: 'ui.action.library',
    summaryKey: 'activity.library.summary',
    resultKey: 'activity.library.result',
    minAge: 12,
    cost: 0,
    icon: 'fluent-emoji-flat:books',
    effects: { attributes: { smarts: 3, happiness: 1 }, school: { stress: -1 } },
  },
  {
    id: 'gardening',
    titleKey: 'ui.action.gardening',
    summaryKey: 'activity.gardening.summary',
    resultKey: 'activity.gardening.result',
    minAge: 12,
    cost: 20,
    icon: 'fluent-emoji-flat:potted-plant',
    effects: { attributes: { health: 2, happiness: 3 }, money: -20, school: { stress: -2 } },
  },
  {
    id: 'gym',
    titleKey: 'ui.action.gym',
    summaryKey: 'activity.gym.summary',
    resultKey: 'activity.gym.result',
    minAge: 12,
    cost: 60,
    icon: 'fluent-emoji-flat:person-lifting-weights',
    effects: { attributes: { health: 6, looks: 2 }, money: -60 },
  },
  {
    id: 'meditate',
    titleKey: 'ui.action.meditate',
    summaryKey: 'activity.meditate.summary',
    resultKey: 'activity.meditate.result',
    minAge: 10,
    cost: 0,
    icon: 'fluent-emoji-flat:person-in-lotus-position',
    effects: { attributes: { happiness: 3, health: 1 }, school: { stress: -8 }, removeStatus: 'stressed' },
  },
  {
    id: 'acting_lessons',
    titleKey: 'ui.action.actingLessons',
    summaryKey: 'activity.actingLessons.summary',
    resultKey: 'activity.actingLessons.result',
    minAge: 8,
    cost: 90,
    icon: 'fluent-emoji-flat:performing-arts',
    effects: { attributes: { looks: 2, happiness: 2, smarts: 1 }, money: -90 },
  },
  {
    id: 'voice_lessons',
    titleKey: 'ui.action.voiceLessons',
    summaryKey: 'activity.voiceLessons.summary',
    resultKey: 'activity.voiceLessons.result',
    minAge: 8,
    cost: 80,
    icon: 'fluent-emoji-flat:microphone',
    effects: { attributes: { happiness: 2, looks: 1, smarts: 1 }, money: -80 },
  },
  {
    id: 'memory_test',
    titleKey: 'ui.action.memoryTest',
    summaryKey: 'activity.memoryTest.summary',
    resultKey: 'activity.memoryTest.result',
    minAge: 6,
    cost: 0,
    icon: 'fluent-emoji-flat:brain',
    effects: { attributes: { smarts: 3 } },
  },
  {
    id: 'instrument_lessons',
    titleKey: 'ui.action.instrumentLessons',
    summaryKey: 'activity.instrumentLessons.summary',
    resultKey: 'activity.instrumentLessons.result',
    minAge: 6,
    cost: 100,
    icon: 'fluent-emoji-flat:musical-keyboard',
    effects: { attributes: { happiness: 2, smarts: 2 }, money: -100 },
  },
  {
    id: 'space_camp',
    titleKey: 'ui.action.spaceCamp',
    summaryKey: 'activity.spaceCamp.summary',
    resultKey: 'activity.spaceCamp.result',
    minAge: 10,
    cost: 300,
    icon: 'fluent-emoji-flat:rocket',
    effects: { attributes: { smarts: 5, happiness: 3 }, money: -300 },
  },
  {
    id: 'modeling_lessons',
    titleKey: 'ui.action.modelingLessons',
    summaryKey: 'activity.modelingLessons.summary',
    resultKey: 'activity.modelingLessons.result',
    minAge: 8,
    cost: 120,
    icon: 'fluent-emoji-flat:dress',
    effects: { attributes: { looks: 4, happiness: 1 }, money: -120 },
  },
  {
    id: 'diet',
    titleKey: 'ui.action.diet',
    summaryKey: 'activity.diet.summary',
    resultKey: 'activity.diet.result',
    minAge: 18,
    cost: 140,
    icon: 'fluent-emoji-flat:green-salad',
    effects: { attributes: { health: 4, looks: 1 }, money: -140 },
  },
  {
    id: 'alternative_doctor',
    titleKey: 'ui.action.alternativeDoctor',
    summaryKey: 'activity.alternativeDoctor.summary',
    resultKey: 'activity.alternativeDoctor.result',
    minAge: 18,
    cost: 120,
    icon: 'fluent-emoji-flat:herb',
    effects: { attributes: { health: 4, happiness: 1 }, money: -120 },
  },
  {
    id: 'psychiatrist',
    titleKey: 'ui.action.psychiatrist',
    summaryKey: 'activity.psychiatrist.summary',
    resultKey: 'activity.psychiatrist.result',
    minAge: 18,
    cost: 180,
    icon: 'fluent-emoji-flat:thought-balloon',
    effects: { attributes: { happiness: 6, health: 1 }, money: -180, removeStatus: 'stressed' },
  },
  {
    id: 'witch_doctor',
    titleKey: 'ui.action.witchDoctor',
    summaryKey: 'activity.witchDoctor.summary',
    resultKey: 'activity.witchDoctor.result',
    minAge: 18,
    cost: 90,
    icon: 'fluent-emoji-flat:crystal-ball',
    effects: { attributes: { health: -2, happiness: 4 }, money: -90, addStatus: 'weirded_out' },
  },
  {
    id: 'donate_blood',
    titleKey: 'ui.action.donateBlood',
    summaryKey: 'activity.donateBlood.summary',
    resultKey: 'activity.donateBlood.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:drop-of-blood',
    effects: { attributes: { happiness: 3, health: -1 } },
  },
  {
    id: 'donate_plasma',
    titleKey: 'ui.action.donatePlasma',
    summaryKey: 'activity.donatePlasma.summary',
    resultKey: 'activity.donatePlasma.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:test-tube',
    effects: { attributes: { happiness: 2, health: -1 } },
  },
  {
    id: 'fertility',
    titleKey: 'ui.action.fertility',
    summaryKey: 'activity.fertility.summary',
    resultKey: 'activity.fertility.result',
    minAge: 18,
    cost: 250,
    icon: 'fluent-emoji-flat:baby',
    effects: { attributes: { happiness: 1, smarts: 1 }, money: -250 },
  },
  {
    id: 'love',
    titleKey: 'ui.action.love',
    summaryKey: 'activity.love.summary',
    resultKey: 'activity.love.result',
    minAge: 14,
    cost: 0,
    icon: 'fluent-emoji-flat:heart-with-arrow',
    effects: { attributes: { happiness: 5, looks: 1 } },
  },
  {
    id: 'nightlife',
    titleKey: 'ui.action.nightlife',
    summaryKey: 'activity.nightlife.summary',
    resultKey: 'activity.nightlife.result',
    minAge: 18,
    cost: 80,
    icon: 'fluent-emoji-flat:cocktail-glass',
    effects: { attributes: { happiness: 5, health: -2 }, money: -80, addStatus: 'partied' },
  },
  {
    id: 'salon_spa',
    titleKey: 'ui.action.salonSpa',
    summaryKey: 'activity.salonSpa.summary',
    resultKey: 'activity.salonSpa.result',
    minAge: 14,
    cost: 90,
    icon: 'fluent-emoji-flat:nail-polish',
    effects: { attributes: { looks: 5, happiness: 2 }, money: -90 },
  },
  {
    id: 'licenses',
    titleKey: 'ui.action.licenses',
    summaryKey: 'activity.licenses.summary',
    resultKey: 'activity.licenses.result',
    minAge: 16,
    cost: 120,
    icon: 'fluent-emoji-flat:automobile',
    effects: { attributes: { smarts: 2, happiness: 1 }, money: -120, addStatus: 'licensed' },
  },
  {
    id: 'lawsuit',
    titleKey: 'ui.action.lawsuit',
    summaryKey: 'activity.lawsuit.summary',
    resultKey: 'activity.lawsuit.result',
    minAge: 18,
    cost: 500,
    icon: 'fluent-emoji-flat:balance-scale',
    effects: { attributes: { happiness: -2, smarts: 2 }, money: -500 },
  },
  {
    id: 'casino',
    titleKey: 'ui.action.casino',
    summaryKey: 'activity.casino.summary',
    resultKey: 'activity.casino.result',
    minAge: 18,
    cost: 100,
    icon: 'fluent-emoji-flat:spade-suit',
    effects: { attributes: { happiness: 3, smarts: -1 }, money: -100 },
  },
  {
    id: 'horse_races',
    titleKey: 'ui.action.horseRaces',
    summaryKey: 'activity.horseRaces.summary',
    resultKey: 'activity.horseRaces.result',
    minAge: 18,
    cost: 75,
    icon: 'fluent-emoji-flat:horse-racing',
    effects: { attributes: { happiness: 2 }, money: -75 },
  },
  {
    id: 'lottery',
    titleKey: 'ui.action.lottery',
    summaryKey: 'activity.lottery.summary',
    resultKey: 'activity.lottery.result',
    minAge: 18,
    cost: 10,
    icon: 'fluent-emoji-flat:ticket',
    effects: { attributes: { happiness: 1 }, money: -10 },
  },
  {
    id: 'sweepstakes',
    titleKey: 'ui.action.sweepstakes',
    summaryKey: 'activity.sweepstakes.summary',
    resultKey: 'activity.sweepstakes.result',
    minAge: 18,
    cost: 1,
    icon: 'fluent-emoji-flat:wrapped-gift',
    effects: { attributes: { happiness: 1 }, money: -1 },
  },
  {
    id: 'vacation',
    titleKey: 'ui.action.vacation',
    summaryKey: 'activity.vacation.summary',
    resultKey: 'activity.vacation.result',
    minAge: 18,
    cost: 800,
    icon: 'fluent-emoji-flat:desert-island',
    effects: { attributes: { happiness: 10, health: 2 }, money: -800, removeStatus: 'stressed' },
  },
  {
    id: 'emigrate',
    titleKey: 'ui.action.emigrate',
    summaryKey: 'activity.emigrate.summary',
    resultKey: 'activity.emigrate.result',
    minAge: 18,
    cost: 1000,
    icon: 'fluent-emoji-flat:globe-showing-americas',
    effects: { attributes: { happiness: 3, smarts: 2 }, money: -1000, addStatus: 'relocated' },
  },
  {
    id: 'adoption',
    titleKey: 'ui.action.adoption',
    summaryKey: 'activity.adoption.summary',
    resultKey: 'activity.adoption.result',
    minAge: 18,
    cost: 1500,
    icon: 'fluent-emoji-flat:teddy-bear',
    effects: { attributes: { happiness: 6 }, money: -1500, addStatus: 'family_planning' },
  },
  {
    id: 'shopping',
    titleKey: 'ui.action.shopping',
    summaryKey: 'activity.shopping.summary',
    resultKey: 'activity.shopping.result',
    minAge: 18,
    cost: 250,
    icon: 'fluent-emoji-flat:shopping-bags',
    effects: { attributes: { happiness: 3, looks: 1 }, money: -250 },
  },
  {
    id: 'pets',
    titleKey: 'ui.action.pets',
    summaryKey: 'activity.pets.summary',
    resultKey: 'activity.pets.result',
    minAge: 6,
    cost: 120,
    icon: 'fluent-emoji-flat:paw-prints',
    effects: { attributes: { happiness: 5 }, money: -120 },
  },
  {
    id: 'plastic_surgery',
    titleKey: 'ui.action.plasticSurgery',
    summaryKey: 'activity.plasticSurgery.summary',
    resultKey: 'activity.plasticSurgery.result',
    minAge: 18,
    cost: 2500,
    icon: 'fluent-emoji-flat:lipstick',
    effects: { attributes: { looks: 8, health: -2 }, money: -2500 },
  },
  {
    id: 'pray',
    titleKey: 'ui.action.pray',
    summaryKey: 'activity.pray.summary',
    resultKey: 'activity.pray.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:folded-hands',
    effects: { attributes: { happiness: 2 } },
  },
  {
    id: 'rehab',
    titleKey: 'ui.action.rehab',
    summaryKey: 'activity.rehab.summary',
    resultKey: 'activity.rehab.result',
    minAge: 18,
    cost: 700,
    icon: 'fluent-emoji-flat:medical-symbol',
    effects: { attributes: { health: 5, happiness: -1 }, money: -700, removeStatus: 'partied' },
  },
  {
    id: 'social_media',
    titleKey: 'ui.action.socialMedia',
    summaryKey: 'activity.socialMedia.summary',
    resultKey: 'activity.socialMedia.result',
    minAge: 13,
    cost: 0,
    icon: 'fluent-emoji-flat:mobile-phone',
    effects: { attributes: { happiness: 2, looks: 1 }, addStatus: 'online' },
  },
  {
    id: 'fame',
    titleKey: 'ui.action.fame',
    summaryKey: 'activity.fame.summary',
    resultKey: 'activity.fame.result',
    minAge: 18,
    cost: 150,
    icon: 'fluent-emoji-flat:star-struck',
    effects: { attributes: { looks: 2, happiness: 2 }, money: -150, addStatus: 'public' },
  },
  {
    id: 'royalty',
    titleKey: 'ui.action.royalty',
    summaryKey: 'activity.royalty.summary',
    resultKey: 'activity.royalty.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:crown',
    effects: { attributes: { happiness: 1, smarts: 1 }, addStatus: 'civic' },
  },
  {
    id: 'time_machine',
    titleKey: 'ui.action.timeMachine',
    summaryKey: 'activity.timeMachine.summary',
    resultKey: 'activity.timeMachine.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:hourglass-done',
    effects: { attributes: { smarts: 1, happiness: -1 } },
  },
  {
    id: 'zoo_trip',
    titleKey: 'ui.action.zooTrip',
    summaryKey: 'activity.zooTrip.summary',
    resultKey: 'activity.zooTrip.result',
    minAge: 0,
    cost: 35,
    icon: 'fluent-emoji-flat:elephant',
    effects: { attributes: { happiness: 4, smarts: 1 }, money: -35 },
  },
  {
    id: 'will',
    titleKey: 'ui.action.will',
    summaryKey: 'activity.will.summary',
    resultKey: 'activity.will.result',
    minAge: 18,
    cost: 100,
    icon: 'fluent-emoji-flat:memo',
    effects: { attributes: { smarts: 2, happiness: -1 }, money: -100, addStatus: 'has_will' },
  },
  {
    id: 'surrender',
    titleKey: 'ui.action.surrender',
    summaryKey: 'activity.surrender.summary',
    resultKey: 'activity.surrender.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:white-flag',
    effects: { attributes: { happiness: -8, health: -6 } },
  },
  {
    id: 'crime',
    titleKey: 'ui.action.crime',
    summaryKey: 'activity.crime.summary',
    resultKey: 'activity.crime.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:detective',
    effects: { attributes: { happiness: -4, health: -1 }, money: 120, addStatus: 'suspicious' },
  },
  {
    id: 'overtime',
    titleKey: 'ui.action.overtime',
    summaryKey: 'activity.overtime.summary',
    resultKey: 'activity.overtime.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:briefcase',
    effects: { attributes: { health: -2, happiness: -1 }, money: 180 },
  },
  {
    id: 'find_job',
    titleKey: 'ui.action.findJob',
    summaryKey: 'activity.findJob.summary',
    resultKey: 'activity.findJob.result',
    minAge: 18,
    cost: 0,
    icon: 'fluent-emoji-flat:magnifying-glass-tilted-left',
    effects: {},
  },
];
