import type { LifeEvent } from '../game/types';

export const events: LifeEvent[] = [
  {
    id: 'birth_sunny',
    textKey: 'event.birth.sunny.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'calm',
        textKey: 'event.birth.sunny.choice.calm',
        resultKey: 'event.birth.sunny.result.calm',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'birth_rainy',
    textKey: 'event.birth.rainy.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'listen',
        textKey: 'event.birth.rainy.choice.listen',
        resultKey: 'event.birth.rainy.result.listen',
        effects: { attributes: { happiness: 1, health: 1 } },
      },
    ],
  },
  {
    id: 'birth_busy_home',
    textKey: 'event.birth.busyHome.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'cling',
        textKey: 'event.birth.busyHome.choice.cling',
        resultKey: 'event.birth.busyHome.result.cling',
        effects: { attributes: { happiness: 2 }, relationship: { type: 'mother', closeness: 2 } },
      },
    ],
  },
  {
    id: 'child_book',
    textKey: 'event.child.book.text',
    minAge: 3,
    maxAge: 8,
    weight: 2,
    tags: ['child', 'school'],
    choices: [
      {
        id: 'read',
        textKey: 'event.child.book.choice.read',
        resultKey: 'event.child.book.result.read',
        effects: { attributes: { smarts: 4, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_neighbor',
    textKey: 'event.child.neighbor.text',
    minAge: 4,
    maxAge: 10,
    weight: 1,
    tags: ['child', 'social'],
    choices: [
      {
        id: 'share',
        textKey: 'event.child.neighbor.choice.share',
        resultKey: 'event.child.neighbor.result.share',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'child_lost_toy',
    textKey: 'event.child.lostToy.text',
    minAge: 3,
    maxAge: 8,
    weight: 1,
    tags: ['child', 'family'],
    choices: [
      {
        id: 'search',
        textKey: 'event.child.lostToy.choice.search',
        resultKey: 'event.child.lostToy.result.search',
        effects: { attributes: { smarts: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_tree_climb',
    textKey: 'event.child.treeClimb.text',
    minAge: 5,
    maxAge: 11,
    weight: 1,
    tags: ['child', 'health'],
    choices: [
      {
        id: 'careful',
        textKey: 'event.child.treeClimb.choice.careful',
        resultKey: 'event.child.treeClimb.result.careful',
        effects: { attributes: { health: 2, happiness: 2 } },
      },
      {
        id: 'showOff',
        textKey: 'event.child.treeClimb.choice.showOff',
        resultKey: 'event.child.treeClimb.result.showOff',
        effects: { attributes: { health: -3, happiness: 3 } },
      },
    ],
  },
  {
    id: 'school_test',
    textKey: 'event.school.test.text',
    minAge: 7,
    maxAge: 17,
    weight: 2,
    tags: ['school'],
    requires: { schoolStage: 'elementary' },
    choices: [
      {
        id: 'study',
        textKey: 'event.school.test.choice.study',
        resultKey: 'event.school.test.result.study',
        effects: { attributes: { smarts: 4, happiness: -1 } },
      },
    ],
  },
  {
    id: 'school_group_project',
    textKey: 'event.school.groupProject.text',
    minAge: 9,
    maxAge: 17,
    weight: 1,
    tags: ['school', 'social'],
    requires: { schoolStage: 'middle' },
    choices: [
      {
        id: 'coordinate',
        textKey: 'event.school.groupProject.choice.coordinate',
        resultKey: 'event.school.groupProject.result.coordinate',
        effects: { attributes: { smarts: 3, happiness: 1 } },
      },
    ],
  },
  {
    id: 'school_bully_choice',
    textKey: 'event.school.bullyChoice.text',
    minAge: 8,
    maxAge: 16,
    weight: 1,
    tags: ['school', 'social'],
    choices: [
      {
        id: 'help',
        textKey: 'event.school.bullyChoice.choice.help',
        resultKey: 'event.school.bullyChoice.result.help',
        effects: { attributes: { happiness: 2, health: -1 } },
      },
    ],
  },
  {
    id: 'school_art_day',
    textKey: 'event.school.artDay.text',
    minAge: 6,
    maxAge: 16,
    weight: 1,
    tags: ['school', 'creative'],
    choices: [
      {
        id: 'paint',
        textKey: 'event.school.artDay.choice.paint',
        resultKey: 'event.school.artDay.result.paint',
        effects: { attributes: { happiness: 3, looks: 1 } },
      },
    ],
  },
  {
    id: 'school_sports_day',
    textKey: 'event.school.sportsDay.text',
    minAge: 6,
    maxAge: 17,
    weight: 1,
    tags: ['school', 'health'],
    choices: [
      {
        id: 'run',
        textKey: 'event.school.sportsDay.choice.run',
        resultKey: 'event.school.sportsDay.result.run',
        effects: { attributes: { health: 4, happiness: 1 } },
      },
    ],
  },
  {
    id: 'family_meal',
    textKey: 'event.family.meal.text',
    minAge: 4,
    maxAge: 80,
    weight: 2,
    tags: ['family'],
    choices: [
      {
        id: 'talk',
        textKey: 'event.family.meal.choice.talk',
        resultKey: 'event.family.meal.result.talk',
        effects: { attributes: { happiness: 3 }, relationship: { type: 'mother', closeness: 2 } },
      },
    ],
  },
  {
    id: 'family_argument',
    textKey: 'event.family.argument.text',
    minAge: 7,
    maxAge: 60,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'listen',
        textKey: 'event.family.argument.choice.listen',
        resultKey: 'event.family.argument.result.listen',
        effects: { attributes: { smarts: 1, happiness: -1 }, relationship: { type: 'father', closeness: 1 } },
      },
      {
        id: 'leave',
        textKey: 'event.family.argument.choice.leave',
        resultKey: 'event.family.argument.result.leave',
        effects: { attributes: { happiness: 1 } },
      },
    ],
  },
  {
    id: 'family_sibling_game',
    textKey: 'event.family.siblingGame.text',
    minAge: 4,
    maxAge: 18,
    weight: 1,
    tags: ['family', 'social'],
    choices: [
      {
        id: 'play',
        textKey: 'event.family.siblingGame.choice.play',
        resultKey: 'event.family.siblingGame.result.play',
        effects: { attributes: { happiness: 4 }, relationship: { type: 'sibling', closeness: 3 } },
      },
    ],
  },
  {
    id: 'family_parent_tired',
    textKey: 'event.family.parentTired.text',
    minAge: 10,
    maxAge: 35,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'help',
        textKey: 'event.family.parentTired.choice.help',
        resultKey: 'event.family.parentTired.result.help',
        effects: { attributes: { happiness: 1 }, relationship: { type: 'mother', closeness: 3 } },
      },
    ],
  },
  {
    id: 'adult_walk',
    textKey: 'event.adult.walk.text',
    minAge: 18,
    maxAge: 70,
    weight: 2,
    tags: ['adult', 'health'],
    choices: [
      {
        id: 'walk',
        textKey: 'event.adult.walk.choice.walk',
        resultKey: 'event.adult.walk.result.walk',
        effects: { attributes: { health: 3, happiness: 2 } },
      },
    ],
  },
  {
    id: 'adult_room_clean',
    textKey: 'event.adult.roomClean.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'sort',
        textKey: 'event.adult.roomClean.choice.sort',
        resultKey: 'event.adult.roomClean.result.sort',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'adult_old_friend',
    textKey: 'event.adult.oldFriend.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['adult', 'social'],
    choices: [
      {
        id: 'reply',
        textKey: 'event.adult.oldFriend.choice.reply',
        resultKey: 'event.adult.oldFriend.result.reply',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'adult_bad_sleep',
    textKey: 'event.adult.badSleep.text',
    minAge: 18,
    maxAge: 75,
    weight: 1,
    tags: ['adult', 'health'],
    choices: [
      {
        id: 'slow',
        textKey: 'event.adult.badSleep.choice.slow',
        resultKey: 'event.adult.badSleep.result.slow',
        effects: { attributes: { health: 1, happiness: -1 } },
      },
    ],
  },
  {
    id: 'work_rush',
    textKey: 'event.work.rush.text',
    minAge: 18,
    maxAge: 65,
    weight: 2,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'focus',
        textKey: 'event.work.rush.choice.focus',
        resultKey: 'event.work.rush.result.focus',
        effects: { attributes: { smarts: 2, happiness: -2, health: -1 } },
      },
    ],
  },
  {
    id: 'work_kind_customer',
    textKey: 'event.work.kindCustomer.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work', 'social'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'thank',
        textKey: 'event.work.kindCustomer.choice.thank',
        resultKey: 'event.work.kindCustomer.result.thank',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'work_mistake',
    textKey: 'event.work.mistake.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'own',
        textKey: 'event.work.mistake.choice.own',
        resultKey: 'event.work.mistake.result.own',
        effects: { attributes: { smarts: 2, happiness: -2 } },
      },
    ],
  },
  {
    id: 'work_extra_shift',
    textKey: 'event.work.extraShift.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work', 'money'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'accept',
        textKey: 'event.work.extraShift.choice.accept',
        resultKey: 'event.work.extraShift.result.accept',
        effects: { attributes: { health: -2, happiness: -1 }, money: 300 },
      },
      {
        id: 'decline',
        textKey: 'event.work.extraShift.choice.decline',
        resultKey: 'event.work.extraShift.result.decline',
        effects: { attributes: { health: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'money_wallet',
    textKey: 'event.money.wallet.text',
    minAge: 10,
    maxAge: 80,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'return',
        textKey: 'event.money.wallet.choice.return',
        resultKey: 'event.money.wallet.result.return',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'money_small_bonus',
    textKey: 'event.money.smallBonus.text',
    minAge: 18,
    maxAge: 70,
    weight: 1,
    tags: ['money', 'work'],
    choices: [
      {
        id: 'save',
        textKey: 'event.money.smallBonus.choice.save',
        resultKey: 'event.money.smallBonus.result.save',
        effects: { attributes: { smarts: 1 }, money: 500 },
      },
    ],
  },
  {
    id: 'money_broken_phone',
    textKey: 'event.money.brokenPhone.text',
    minAge: 13,
    maxAge: 70,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'repair',
        textKey: 'event.money.brokenPhone.choice.repair',
        resultKey: 'event.money.brokenPhone.result.repair',
        effects: { attributes: { happiness: -1 }, money: -400 },
      },
    ],
  },
  {
    id: 'health_minor_fever',
    textKey: 'event.health.minorFever.text',
    minAge: 1,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'rest',
        textKey: 'event.health.minorFever.choice.rest',
        resultKey: 'event.health.minorFever.result.rest',
        effects: { attributes: { health: 2, happiness: -1 } },
      },
    ],
  },
  {
    id: 'health_knee_pain',
    textKey: 'event.health.kneePain.text',
    minAge: 35,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'check',
        textKey: 'event.health.kneePain.choice.check',
        resultKey: 'event.health.kneePain.result.check',
        effects: { attributes: { health: 3 }, money: -150 },
      },
    ],
  },
  {
    id: 'elder_quiet_morning',
    textKey: 'event.elder.quietMorning.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'health'],
    choices: [
      {
        id: 'tea',
        textKey: 'event.elder.quietMorning.choice.tea',
        resultKey: 'event.elder.quietMorning.result.tea',
        effects: { attributes: { health: 1, happiness: 3 } },
      },
    ],
  },
  {
    id: 'elder_memory_box',
    textKey: 'event.elder.memoryBox.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'family'],
    choices: [
      {
        id: 'open',
        textKey: 'event.elder.memoryBox.choice.open',
        resultKey: 'event.elder.memoryBox.result.open',
        effects: { attributes: { happiness: 4 }, relationship: { type: 'sibling', closeness: 1 } },
      },
    ],
  },
];
