import type { LifeEvent } from '../game/types';

export const events: LifeEvent[] = [
  {
    id: 'birth_sunny',
    textKey: 'event.birth.sunny.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'calm',
        textKey: 'event.birth.sunny.choice.calm',
        resultKey: 'event.birth.sunny.result.calm',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'birth_rainy',
    textKey: 'event.birth.rainy.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'listen',
        textKey: 'event.birth.rainy.choice.listen',
        resultKey: 'event.birth.rainy.result.listen',
        effects: { attributes: { happiness: 1, health: 1 } },
      },
    ],
  },
  {
    id: 'birth_busy_home',
    textKey: 'event.birth.busyHome.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'cling',
        textKey: 'event.birth.busyHome.choice.cling',
        resultKey: 'event.birth.busyHome.result.cling',
        effects: { attributes: { happiness: 2 }, relationship: { type: 'mother', closeness: 2 } },
      },
    ],
  },
  {
    id: 'birth_quiet_night',
    textKey: 'event.birth.quietNight.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'sleep',
        textKey: 'event.birth.quietNight.choice.sleep',
        resultKey: 'event.birth.quietNight.result.sleep',
        effects: { attributes: { health: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'birth_small_apartment',
    textKey: 'event.birth.smallApartment.text',
    minAge: 0,
    maxAge: 0,
    weight: 1,
    tags: ['birth', 'family'],
    choices: [
      {
        id: 'settle',
        textKey: 'event.birth.smallApartment.choice.settle',
        resultKey: 'event.birth.smallApartment.result.settle',
        effects: { attributes: { happiness: 1 }, relationship: { type: 'father', closeness: 2 } },
      },
    ],
  },
  {
    id: 'child_book',
    textKey: 'event.child.book.text',
    minAge: 3,
    maxAge: 8,
    weight: 2,
    tags: ['child', 'school'],
    choices: [
      {
        id: 'read',
        textKey: 'event.child.book.choice.read',
        resultKey: 'event.child.book.result.read',
        effects: { attributes: { smarts: 4, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_neighbor',
    textKey: 'event.child.neighbor.text',
    minAge: 4,
    maxAge: 10,
    weight: 1,
    tags: ['child', 'social'],
    choices: [
      {
        id: 'share',
        textKey: 'event.child.neighbor.choice.share',
        resultKey: 'event.child.neighbor.result.share',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'child_lost_toy',
    textKey: 'event.child.lostToy.text',
    minAge: 3,
    maxAge: 8,
    weight: 1,
    tags: ['child', 'family'],
    choices: [
      {
        id: 'search',
        textKey: 'event.child.lostToy.choice.search',
        resultKey: 'event.child.lostToy.result.search',
        effects: { attributes: { smarts: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_tree_climb',
    textKey: 'event.child.treeClimb.text',
    minAge: 5,
    maxAge: 11,
    weight: 1,
    tags: ['child', 'health'],
    choices: [
      {
        id: 'careful',
        textKey: 'event.child.treeClimb.choice.careful',
        resultKey: 'event.child.treeClimb.result.careful',
        effects: { attributes: { health: 2, happiness: 2 } },
      },
      {
        id: 'showOff',
        textKey: 'event.child.treeClimb.choice.showOff',
        resultKey: 'event.child.treeClimb.result.showOff',
        effects: { attributes: { health: -3, happiness: 3 } },
      },
    ],
  },
  {
    id: 'child_first_drawing',
    textKey: 'event.child.firstDrawing.text',
    minAge: 3,
    maxAge: 8,
    weight: 1,
    tags: ['child', 'family'],
    choices: [
      {
        id: 'show',
        textKey: 'event.child.firstDrawing.choice.show',
        resultKey: 'event.child.firstDrawing.result.show',
        effects: { attributes: { happiness: 3, looks: 1 }, relationship: { type: 'mother', closeness: 1 } },
      },
    ],
  },
  {
    id: 'child_puddle_jump',
    textKey: 'event.child.puddleJump.text',
    minAge: 3,
    maxAge: 9,
    weight: 1,
    tags: ['child', 'health'],
    choices: [
      {
        id: 'jump',
        textKey: 'event.child.puddleJump.choice.jump',
        resultKey: 'event.child.puddleJump.result.jump',
        effects: { attributes: { happiness: 3, health: -1 } },
      },
      {
        id: 'skip',
        textKey: 'event.child.puddleJump.choice.skip',
        resultKey: 'event.child.puddleJump.result.skip',
        effects: { attributes: { health: 1, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_shared_snack',
    textKey: 'event.child.sharedSnack.text',
    minAge: 4,
    maxAge: 11,
    weight: 1,
    tags: ['child', 'family'],
    choices: [
      {
        id: 'split',
        textKey: 'event.child.sharedSnack.choice.split',
        resultKey: 'event.child.sharedSnack.result.split',
        effects: { attributes: { happiness: 2 }, relationship: { type: 'sibling', closeness: 2 } },
      },
    ],
  },
  {
    id: 'child_library_card',
    textKey: 'event.child.libraryCard.text',
    minAge: 6,
    maxAge: 12,
    weight: 1,
    tags: ['child', 'school'],
    choices: [
      {
        id: 'borrow',
        textKey: 'event.child.libraryCard.choice.borrow',
        resultKey: 'event.child.libraryCard.result.borrow',
        effects: { attributes: { smarts: 3, happiness: 1 } },
      },
    ],
  },
  {
    id: 'child_bedtime_question',
    textKey: 'event.child.bedtimeQuestion.text',
    minAge: 4,
    maxAge: 10,
    weight: 1,
    tags: ['child', 'family'],
    choices: [
      {
        id: 'ask',
        textKey: 'event.child.bedtimeQuestion.choice.ask',
        resultKey: 'event.child.bedtimeQuestion.result.ask',
        effects: { attributes: { smarts: 2, happiness: 1 }, relationship: { type: 'father', closeness: 1 } },
      },
    ],
  },
  {
    id: 'child_music_corner',
    textKey: 'event.child.musicCorner.text',
    minAge: 5,
    maxAge: 12,
    weight: 1,
    tags: ['child'],
    choices: [
      {
        id: 'tap',
        textKey: 'event.child.musicCorner.choice.tap',
        resultKey: 'event.child.musicCorner.result.tap',
        effects: { attributes: { happiness: 3, smarts: 1 } },
      },
    ],
  },
  {
    id: 'school_test',
    textKey: 'event.school.test.text',
    minAge: 7,
    maxAge: 17,
    weight: 2,
    tags: ['school'],
    requires: { schoolStage: 'elementary' },
    choices: [
      {
        id: 'study',
        textKey: 'event.school.test.choice.study',
        resultKey: 'event.school.test.result.study',
        effects: { attributes: { smarts: 4, happiness: -1 }, school: { stress: 4 } },
      },
    ],
  },
  {
    id: 'school_group_project',
    textKey: 'event.school.groupProject.text',
    minAge: 9,
    maxAge: 17,
    weight: 1,
    tags: ['school', 'social'],
    requires: { schoolStage: 'middle' },
    choices: [
      {
        id: 'coordinate',
        textKey: 'event.school.groupProject.choice.coordinate',
        resultKey: 'event.school.groupProject.result.coordinate',
        effects: { attributes: { smarts: 3, happiness: 1 } },
      },
    ],
  },
  {
    id: 'school_bully_choice',
    textKey: 'event.school.bullyChoice.text',
    minAge: 8,
    maxAge: 16,
    weight: 1,
    tags: ['school', 'social'],
    choices: [
      {
        id: 'help',
        textKey: 'event.school.bullyChoice.choice.help',
        resultKey: 'event.school.bullyChoice.result.help',
        effects: { attributes: { happiness: 2, health: -1 } },
      },
    ],
  },
  {
    id: 'school_art_day',
    textKey: 'event.school.artDay.text',
    minAge: 6,
    maxAge: 16,
    weight: 1,
    tags: ['school', 'creative'],
    choices: [
      {
        id: 'paint',
        textKey: 'event.school.artDay.choice.paint',
        resultKey: 'event.school.artDay.result.paint',
        effects: { attributes: { happiness: 3, looks: 1 } },
      },
    ],
  },
  {
    id: 'school_sports_day',
    textKey: 'event.school.sportsDay.text',
    minAge: 6,
    maxAge: 17,
    weight: 1,
    tags: ['school', 'health'],
    choices: [
      {
        id: 'run',
        textKey: 'event.school.sportsDay.choice.run',
        resultKey: 'event.school.sportsDay.result.run',
        effects: { attributes: { health: 4, happiness: 1 } },
      },
    ],
  },
  {
    id: 'school_science_board',
    textKey: 'event.school.scienceBoard.text',
    minAge: 8,
    maxAge: 11,
    weight: 1,
    tags: ['school'],
    requires: { schoolStage: 'elementary' },
    choices: [
      {
        id: 'explain',
        textKey: 'event.school.scienceBoard.choice.explain',
        resultKey: 'event.school.scienceBoard.result.explain',
        effects: { attributes: { smarts: 3, happiness: 1 } },
      },
    ],
  },
  {
    id: 'school_late_homework',
    textKey: 'event.school.lateHomework.text',
    minAge: 7,
    maxAge: 17,
    weight: 1,
    tags: ['school'],
    choices: [
      {
        id: 'finish',
        textKey: 'event.school.lateHomework.choice.finish',
        resultKey: 'event.school.lateHomework.result.finish',
        effects: { attributes: { smarts: 2, happiness: -1, health: -1 }, school: { stress: 6 } },
      },
      {
        id: 'sleep',
        textKey: 'event.school.lateHomework.choice.sleep',
        resultKey: 'event.school.lateHomework.result.sleep',
        effects: { attributes: { health: 2, happiness: -1 }, school: { stress: -2 } },
      },
    ],
  },
  {
    id: 'school_new_friend',
    textKey: 'event.school.newFriend.text',
    minAge: 6,
    maxAge: 16,
    weight: 1,
    tags: ['school'],
    choices: [
      {
        id: 'sit',
        textKey: 'event.school.newFriend.choice.sit',
        resultKey: 'event.school.newFriend.result.sit',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'school_teacher_praise',
    textKey: 'event.school.teacherPraise.text',
    minAge: 6,
    maxAge: 17,
    weight: 1,
    tags: ['school'],
    choices: [
      {
        id: 'smile',
        textKey: 'event.school.teacherPraise.choice.smile',
        resultKey: 'event.school.teacherPraise.result.smile',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'school_bus_delay',
    textKey: 'event.school.busDelay.text',
    minAge: 6,
    maxAge: 17,
    weight: 1,
    tags: ['school'],
    choices: [
      {
        id: 'wait',
        textKey: 'event.school.busDelay.choice.wait',
        resultKey: 'event.school.busDelay.result.wait',
        effects: { attributes: { happiness: -1, smarts: 1 }, school: { stress: 1 } },
      },
    ],
  },
  {
    id: 'family_meal',
    textKey: 'event.family.meal.text',
    minAge: 4,
    maxAge: 80,
    weight: 2,
    tags: ['family'],
    choices: [
      {
        id: 'talk',
        textKey: 'event.family.meal.choice.talk',
        resultKey: 'event.family.meal.result.talk',
        effects: { attributes: { happiness: 3 }, relationship: { type: 'mother', closeness: 2 } },
      },
    ],
  },
  {
    id: 'family_argument',
    textKey: 'event.family.argument.text',
    minAge: 7,
    maxAge: 60,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'listen',
        textKey: 'event.family.argument.choice.listen',
        resultKey: 'event.family.argument.result.listen',
        effects: { attributes: { smarts: 1, happiness: -1 }, relationship: { type: 'father', closeness: 1 } },
      },
      {
        id: 'leave',
        textKey: 'event.family.argument.choice.leave',
        resultKey: 'event.family.argument.result.leave',
        effects: { attributes: { happiness: 1 } },
      },
    ],
  },
  {
    id: 'family_sibling_game',
    textKey: 'event.family.siblingGame.text',
    minAge: 4,
    maxAge: 18,
    weight: 1,
    tags: ['family', 'social'],
    choices: [
      {
        id: 'play',
        textKey: 'event.family.siblingGame.choice.play',
        resultKey: 'event.family.siblingGame.result.play',
        effects: { attributes: { happiness: 4 }, relationship: { type: 'sibling', closeness: 3 } },
      },
    ],
  },
  {
    id: 'family_parent_tired',
    textKey: 'event.family.parentTired.text',
    minAge: 10,
    maxAge: 35,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'help',
        textKey: 'event.family.parentTired.choice.help',
        resultKey: 'event.family.parentTired.result.help',
        effects: { attributes: { happiness: 1 }, relationship: { type: 'mother', closeness: 3 } },
      },
    ],
  },
  {
    id: 'family_weekend_cleaning',
    textKey: 'event.family.weekendCleaning.text',
    minAge: 8,
    maxAge: 60,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'join',
        textKey: 'event.family.weekendCleaning.choice.join',
        resultKey: 'event.family.weekendCleaning.result.join',
        effects: { attributes: { health: 1, happiness: 1 }, relationship: { type: 'mother', closeness: 1 } },
      },
    ],
  },
  {
    id: 'family_small_gift',
    textKey: 'event.family.smallGift.text',
    minAge: 6,
    maxAge: 70,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'thank',
        textKey: 'event.family.smallGift.choice.thank',
        resultKey: 'event.family.smallGift.result.thank',
        effects: { attributes: { happiness: 3 }, relationship: { type: 'father', closeness: 1 } },
      },
    ],
  },
  {
    id: 'family_photo_album',
    textKey: 'event.family.photoAlbum.text',
    minAge: 10,
    maxAge: 80,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'look',
        textKey: 'event.family.photoAlbum.choice.look',
        resultKey: 'event.family.photoAlbum.result.look',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'family_sick_parent',
    textKey: 'event.family.sickParent.text',
    minAge: 12,
    maxAge: 55,
    weight: 1,
    tags: ['family', 'health'],
    choices: [
      {
        id: 'care',
        textKey: 'event.family.sickParent.choice.care',
        resultKey: 'event.family.sickParent.result.care',
        effects: { attributes: { happiness: 1, health: -1 }, relationship: { type: 'mother', closeness: 2 } },
      },
    ],
  },
  {
    id: 'family_shared_errand',
    textKey: 'event.family.sharedErrand.text',
    minAge: 7,
    maxAge: 70,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'carry',
        textKey: 'event.family.sharedErrand.choice.carry',
        resultKey: 'event.family.sharedErrand.result.carry',
        effects: { attributes: { health: 1, happiness: 1 }, relationship: { type: 'father', closeness: 1 } },
      },
    ],
  },
  {
    id: 'family_holiday_call',
    textKey: 'event.family.holidayCall.text',
    minAge: 14,
    maxAge: 85,
    weight: 1,
    tags: ['family'],
    choices: [
      {
        id: 'answer',
        textKey: 'event.family.holidayCall.choice.answer',
        resultKey: 'event.family.holidayCall.result.answer',
        effects: { attributes: { happiness: 2 }, relationship: { type: 'sibling', closeness: 1 } },
      },
    ],
  },
  {
    id: 'adult_walk',
    textKey: 'event.adult.walk.text',
    minAge: 18,
    maxAge: 70,
    weight: 2,
    tags: ['adult', 'health'],
    choices: [
      {
        id: 'walk',
        textKey: 'event.adult.walk.choice.walk',
        resultKey: 'event.adult.walk.result.walk',
        effects: { attributes: { health: 3, happiness: 2 } },
      },
    ],
  },
  {
    id: 'adult_room_clean',
    textKey: 'event.adult.roomClean.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'sort',
        textKey: 'event.adult.roomClean.choice.sort',
        resultKey: 'event.adult.roomClean.result.sort',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'adult_old_friend',
    textKey: 'event.adult.oldFriend.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['adult', 'social'],
    choices: [
      {
        id: 'reply',
        textKey: 'event.adult.oldFriend.choice.reply',
        resultKey: 'event.adult.oldFriend.result.reply',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'adult_bad_sleep',
    textKey: 'event.adult.badSleep.text',
    minAge: 18,
    maxAge: 75,
    weight: 1,
    tags: ['adult', 'health'],
    choices: [
      {
        id: 'slow',
        textKey: 'event.adult.badSleep.choice.slow',
        resultKey: 'event.adult.badSleep.result.slow',
        effects: { attributes: { health: 1, happiness: -1 } },
      },
    ],
  },
  {
    id: 'adult_crowded_train',
    textKey: 'event.adult.crowdedTrain.text',
    minAge: 18,
    maxAge: 70,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'breathe',
        textKey: 'event.adult.crowdedTrain.choice.breathe',
        resultKey: 'event.adult.crowdedTrain.result.breathe',
        effects: { attributes: { happiness: -1, smarts: 1 } },
      },
    ],
  },
  {
    id: 'adult_new_hobby',
    textKey: 'event.adult.newHobby.text',
    minAge: 18,
    maxAge: 75,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'try',
        textKey: 'event.adult.newHobby.choice.try',
        resultKey: 'event.adult.newHobby.result.try',
        effects: { attributes: { happiness: 3, smarts: 1 }, money: -80 },
      },
    ],
  },
  {
    id: 'adult_quiet_cafe',
    textKey: 'event.adult.quietCafe.text',
    minAge: 18,
    maxAge: 70,
    weight: 1,
    tags: ['adult', 'money'],
    choices: [
      {
        id: 'sit',
        textKey: 'event.adult.quietCafe.choice.sit',
        resultKey: 'event.adult.quietCafe.result.sit',
        effects: { attributes: { happiness: 2 }, money: -30 },
      },
    ],
  },
  {
    id: 'adult_missed_alarm',
    textKey: 'event.adult.missedAlarm.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'hurry',
        textKey: 'event.adult.missedAlarm.choice.hurry',
        resultKey: 'event.adult.missedAlarm.result.hurry',
        effects: { attributes: { happiness: -2, health: -1 } },
      },
    ],
  },
  {
    id: 'adult_neighbor_help',
    textKey: 'event.adult.neighborHelp.text',
    minAge: 18,
    maxAge: 80,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'help',
        textKey: 'event.adult.neighborHelp.choice.help',
        resultKey: 'event.adult.neighborHelp.result.help',
        effects: { attributes: { happiness: 2, health: -1 } },
      },
    ],
  },
  {
    id: 'adult_long_queue',
    textKey: 'event.adult.longQueue.text',
    minAge: 18,
    maxAge: 80,
    weight: 1,
    tags: ['adult'],
    choices: [
      {
        id: 'wait',
        textKey: 'event.adult.longQueue.choice.wait',
        resultKey: 'event.adult.longQueue.result.wait',
        effects: { attributes: { happiness: -1, smarts: 1 } },
      },
    ],
  },
  {
    id: 'work_rush',
    textKey: 'event.work.rush.text',
    minAge: 18,
    maxAge: 65,
    weight: 2,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'focus',
        textKey: 'event.work.rush.choice.focus',
        resultKey: 'event.work.rush.result.focus',
        effects: { attributes: { smarts: 2, happiness: -2, health: -1 } },
      },
    ],
  },
  {
    id: 'work_kind_customer',
    textKey: 'event.work.kindCustomer.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work', 'social'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'thank',
        textKey: 'event.work.kindCustomer.choice.thank',
        resultKey: 'event.work.kindCustomer.result.thank',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'work_mistake',
    textKey: 'event.work.mistake.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'own',
        textKey: 'event.work.mistake.choice.own',
        resultKey: 'event.work.mistake.result.own',
        effects: { attributes: { smarts: 2, happiness: -2 } },
      },
    ],
  },
  {
    id: 'work_extra_shift',
    textKey: 'event.work.extraShift.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work', 'money'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'accept',
        textKey: 'event.work.extraShift.choice.accept',
        resultKey: 'event.work.extraShift.result.accept',
        effects: { attributes: { health: -2, happiness: -1 }, money: 300 },
      },
      {
        id: 'decline',
        textKey: 'event.work.extraShift.choice.decline',
        resultKey: 'event.work.extraShift.result.decline',
        effects: { attributes: { health: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'work_team_lunch',
    textKey: 'event.work.teamLunch.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'join',
        textKey: 'event.work.teamLunch.choice.join',
        resultKey: 'event.work.teamLunch.result.join',
        effects: { attributes: { happiness: 2 }, money: -50 },
      },
    ],
  },
  {
    id: 'work_confusing_email',
    textKey: 'event.work.confusingEmail.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'ask',
        textKey: 'event.work.confusingEmail.choice.ask',
        resultKey: 'event.work.confusingEmail.result.ask',
        effects: { attributes: { smarts: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'work_small_praise',
    textKey: 'event.work.smallPraise.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'note',
        textKey: 'event.work.smallPraise.choice.note',
        resultKey: 'event.work.smallPraise.result.note',
        effects: { attributes: { happiness: 3 } },
      },
    ],
  },
  {
    id: 'work_commute_delay',
    textKey: 'event.work.commuteDelay.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'message',
        textKey: 'event.work.commuteDelay.choice.message',
        resultKey: 'event.work.commuteDelay.result.message',
        effects: { attributes: { happiness: -1, smarts: 1 } },
      },
    ],
  },
  {
    id: 'work_desk_cleanup',
    textKey: 'event.work.deskCleanup.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'tidy',
        textKey: 'event.work.deskCleanup.choice.tidy',
        resultKey: 'event.work.deskCleanup.result.tidy',
        effects: { attributes: { smarts: 1, happiness: 1 } },
      },
    ],
  },
  {
    id: 'work_new_task',
    textKey: 'event.work.newTask.text',
    minAge: 18,
    maxAge: 65,
    weight: 1,
    tags: ['work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'learn',
        textKey: 'event.work.newTask.choice.learn',
        resultKey: 'event.work.newTask.result.learn',
        effects: { attributes: { smarts: 3, happiness: -1 } },
      },
    ],
  },
  {
    id: 'money_wallet',
    textKey: 'event.money.wallet.text',
    minAge: 10,
    maxAge: 80,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'return',
        textKey: 'event.money.wallet.choice.return',
        resultKey: 'event.money.wallet.result.return',
        effects: { attributes: { happiness: 2, smarts: 1 } },
      },
    ],
  },
  {
    id: 'money_small_bonus',
    textKey: 'event.money.smallBonus.text',
    minAge: 18,
    maxAge: 70,
    weight: 1,
    tags: ['money', 'work'],
    requires: { hasJob: true },
    choices: [
      {
        id: 'save',
        textKey: 'event.money.smallBonus.choice.save',
        resultKey: 'event.money.smallBonus.result.save',
        effects: { attributes: { smarts: 1 }, money: 500 },
      },
    ],
  },
  {
    id: 'money_broken_phone',
    textKey: 'event.money.brokenPhone.text',
    minAge: 13,
    maxAge: 70,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'repair',
        textKey: 'event.money.brokenPhone.choice.repair',
        resultKey: 'event.money.brokenPhone.result.repair',
        effects: { attributes: { happiness: -1 }, money: -400 },
      },
    ],
  },
  {
    id: 'money_sale_choice',
    textKey: 'event.money.saleChoice.text',
    minAge: 13,
    maxAge: 80,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'skip',
        textKey: 'event.money.saleChoice.choice.skip',
        resultKey: 'event.money.saleChoice.result.skip',
        effects: { attributes: { smarts: 2, happiness: -1 }, money: 80 },
      },
      {
        id: 'buy',
        textKey: 'event.money.saleChoice.choice.buy',
        resultKey: 'event.money.saleChoice.result.buy',
        effects: { attributes: { happiness: 2 }, money: -120 },
      },
    ],
  },
  {
    id: 'money_unexpected_bill',
    textKey: 'event.money.unexpectedBill.text',
    minAge: 18,
    maxAge: 80,
    weight: 1,
    tags: ['money'],
    choices: [
      {
        id: 'pay',
        textKey: 'event.money.unexpectedBill.choice.pay',
        resultKey: 'event.money.unexpectedBill.result.pay',
        effects: { attributes: { happiness: -2, smarts: 1 }, money: -250 },
      },
    ],
  },
  {
    id: 'health_minor_fever',
    textKey: 'event.health.minorFever.text',
    minAge: 1,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'rest',
        textKey: 'event.health.minorFever.choice.rest',
        resultKey: 'event.health.minorFever.result.rest',
        effects: { attributes: { health: 2, happiness: -1 } },
      },
    ],
  },
  {
    id: 'health_knee_pain',
    textKey: 'event.health.kneePain.text',
    minAge: 35,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'check',
        textKey: 'event.health.kneePain.choice.check',
        resultKey: 'event.health.kneePain.result.check',
        effects: { attributes: { health: 3 }, money: -150 },
      },
    ],
  },
  {
    id: 'health_bad_meal',
    textKey: 'event.health.badMeal.text',
    minAge: 8,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'plain',
        textKey: 'event.health.badMeal.choice.plain',
        resultKey: 'event.health.badMeal.result.plain',
        effects: { attributes: { health: 1, happiness: -1 } },
      },
    ],
  },
  {
    id: 'health_good_sleep',
    textKey: 'event.health.goodSleep.text',
    minAge: 1,
    maxAge: 90,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'wake',
        textKey: 'event.health.goodSleep.choice.wake',
        resultKey: 'event.health.goodSleep.result.wake',
        effects: { attributes: { health: 3, happiness: 2 }, removeStatus: 'tired' },
      },
    ],
  },
  {
    id: 'health_checkup_note',
    textKey: 'event.health.checkupNote.text',
    minAge: 18,
    maxAge: 85,
    weight: 1,
    tags: ['health'],
    choices: [
      {
        id: 'follow',
        textKey: 'event.health.checkupNote.choice.follow',
        resultKey: 'event.health.checkupNote.result.follow',
        effects: { attributes: { health: 2, smarts: 1 }, money: -120 },
      },
    ],
  },
  {
    id: 'elder_quiet_morning',
    textKey: 'event.elder.quietMorning.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'health'],
    choices: [
      {
        id: 'tea',
        textKey: 'event.elder.quietMorning.choice.tea',
        resultKey: 'event.elder.quietMorning.result.tea',
        effects: { attributes: { health: 1, happiness: 3 } },
      },
    ],
  },
  {
    id: 'elder_memory_box',
    textKey: 'event.elder.memoryBox.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'family'],
    choices: [
      {
        id: 'open',
        textKey: 'event.elder.memoryBox.choice.open',
        resultKey: 'event.elder.memoryBox.result.open',
        effects: { attributes: { happiness: 4 }, relationship: { type: 'sibling', closeness: 1 } },
      },
    ],
  },
  {
    id: 'elder_slow_walk',
    textKey: 'event.elder.slowWalk.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'health'],
    choices: [
      {
        id: 'pace',
        textKey: 'event.elder.slowWalk.choice.pace',
        resultKey: 'event.elder.slowWalk.result.pace',
        effects: { attributes: { health: 2, happiness: 1 } },
      },
    ],
  },
  {
    id: 'elder_family_visit',
    textKey: 'event.elder.familyVisit.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder', 'family'],
    choices: [
      {
        id: 'welcome',
        textKey: 'event.elder.familyVisit.choice.welcome',
        resultKey: 'event.elder.familyVisit.result.welcome',
        effects: { attributes: { happiness: 4 }, relationship: { type: 'sibling', closeness: 1 } },
      },
    ],
  },
  {
    id: 'elder_old_song',
    textKey: 'event.elder.oldSong.text',
    minAge: 65,
    maxAge: 100,
    weight: 1,
    tags: ['elder'],
    choices: [
      {
        id: 'hum',
        textKey: 'event.elder.oldSong.choice.hum',
        resultKey: 'event.elder.oldSong.result.hum',
        effects: { attributes: { happiness: 3, health: 1 } },
      },
    ],
  },
];
